// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common2.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_common2_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_common2_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common2_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common2_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common2_2eproto;
namespace foo {
namespace bar2 {
class Information;
struct InformationDefaultTypeInternal;
extern InformationDefaultTypeInternal _Information_default_instance_;
}  // namespace bar2
}  // namespace foo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace foo {
namespace bar2 {

// ===================================================================


// -------------------------------------------------------------------

class Information final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:foo.bar2.Information) */ {
 public:
  inline Information() : Information(nullptr) {}
  ~Information() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Information(
      ::google::protobuf::internal::ConstantInitialized);

  inline Information(const Information& from) : Information(nullptr, from) {}
  inline Information(Information&& from) noexcept
      : Information(nullptr, std::move(from)) {}
  inline Information& operator=(const Information& from) {
    CopyFrom(from);
    return *this;
  }
  inline Information& operator=(Information&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Information& default_instance() {
    return *internal_default_instance();
  }
  static inline const Information* internal_default_instance() {
    return reinterpret_cast<const Information*>(
        &_Information_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Information& a, Information& b) { a.Swap(&b); }
  inline void Swap(Information* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Information* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Information* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Information>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Information& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Information& from) { Information::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Information* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "foo.bar2.Information"; }

 protected:
  explicit Information(::google::protobuf::Arena* arena);
  Information(::google::protobuf::Arena* arena, const Information& from);
  Information(::google::protobuf::Arena* arena, Information&& from) noexcept
      : Information(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInfoId1FieldNumber = 1,
    kInfoId2FieldNumber = 2,
  };
  // string info_id1 = 1;
  void clear_info_id1() ;
  const std::string& info_id1() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_info_id1(Arg_&& arg, Args_... args);
  std::string* mutable_info_id1();
  PROTOBUF_NODISCARD std::string* release_info_id1();
  void set_allocated_info_id1(std::string* value);

  private:
  const std::string& _internal_info_id1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_info_id1(
      const std::string& value);
  std::string* _internal_mutable_info_id1();

  public:
  // string info_id2 = 2;
  void clear_info_id2() ;
  const std::string& info_id2() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_info_id2(Arg_&& arg, Args_... args);
  std::string* mutable_info_id2();
  PROTOBUF_NODISCARD std::string* release_info_id2();
  void set_allocated_info_id2(std::string* value);

  private:
  const std::string& _internal_info_id2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_info_id2(
      const std::string& value);
  std::string* _internal_mutable_info_id2();

  public:
  // @@protoc_insertion_point(class_scope:foo.bar2.Information)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      45, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Information_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Information& from_msg);
    ::google::protobuf::internal::ArenaStringPtr info_id1_;
    ::google::protobuf::internal::ArenaStringPtr info_id2_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common2_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Information

// string info_id1 = 1;
inline void Information::clear_info_id1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id1_.ClearToEmpty();
}
inline const std::string& Information::info_id1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:foo.bar2.Information.info_id1)
  return _internal_info_id1();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Information::set_info_id1(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id1_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:foo.bar2.Information.info_id1)
}
inline std::string* Information::mutable_info_id1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_info_id1();
  // @@protoc_insertion_point(field_mutable:foo.bar2.Information.info_id1)
  return _s;
}
inline const std::string& Information::_internal_info_id1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.info_id1_.Get();
}
inline void Information::_internal_set_info_id1(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id1_.Set(value, GetArena());
}
inline std::string* Information::_internal_mutable_info_id1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.info_id1_.Mutable( GetArena());
}
inline std::string* Information::release_info_id1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:foo.bar2.Information.info_id1)
  return _impl_.info_id1_.Release();
}
inline void Information::set_allocated_info_id1(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id1_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.info_id1_.IsDefault()) {
          _impl_.info_id1_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:foo.bar2.Information.info_id1)
}

// string info_id2 = 2;
inline void Information::clear_info_id2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id2_.ClearToEmpty();
}
inline const std::string& Information::info_id2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:foo.bar2.Information.info_id2)
  return _internal_info_id2();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Information::set_info_id2(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id2_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:foo.bar2.Information.info_id2)
}
inline std::string* Information::mutable_info_id2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_info_id2();
  // @@protoc_insertion_point(field_mutable:foo.bar2.Information.info_id2)
  return _s;
}
inline const std::string& Information::_internal_info_id2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.info_id2_.Get();
}
inline void Information::_internal_set_info_id2(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id2_.Set(value, GetArena());
}
inline std::string* Information::_internal_mutable_info_id2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.info_id2_.Mutable( GetArena());
}
inline std::string* Information::release_info_id2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:foo.bar2.Information.info_id2)
  return _impl_.info_id2_.Release();
}
inline void Information::set_allocated_info_id2(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.info_id2_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.info_id2_.IsDefault()) {
          _impl_.info_id2_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:foo.bar2.Information.info_id2)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace bar2
}  // namespace foo


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_common2_2eproto_2epb_2eh
