// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: developer.proto
// Protobuf C++ Version: 5.28.3

#include "developer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Other::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : v1_{0},
        v2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Other::Other(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OtherDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OtherDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OtherDefaultTypeInternal() {}
  union {
    Other _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OtherDefaultTypeInternal _Other_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Developer_MapEntry_DoNotUse::Developer_MapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Developer_MapEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Developer_MapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Developer_MapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Developer_MapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Developer_MapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Developer_MapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Developer_MapEntry_DoNotUseDefaultTypeInternal _Developer_MapEntry_DoNotUse_default_instance_;

inline constexpr Developer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        list_{},
        _list_cached_byte_size_{0},
        map_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        other_{nullptr},
        week_{static_cast< ::Week >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Developer::Developer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeveloperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeveloperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeveloperDefaultTypeInternal() {}
  union {
    Developer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeveloperDefaultTypeInternal _Developer_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_developer_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_developer_2eproto = nullptr;
const ::uint32_t
    TableStruct_developer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Other, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Other, _impl_.v1_),
        PROTOBUF_FIELD_OFFSET(::Other, _impl_.v2_),
        PROTOBUF_FIELD_OFFSET(::Developer_MapEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Developer_MapEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Developer_MapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Developer_MapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Developer, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_.week_),
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_.list_),
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_.map_),
        PROTOBUF_FIELD_OFFSET(::Developer, _impl_.other_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Other)},
        {10, 20, -1, sizeof(::Developer_MapEntry_DoNotUse)},
        {22, 35, -1, sizeof(::Developer)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Other_default_instance_._instance,
    &::_Developer_MapEntry_DoNotUse_default_instance_._instance,
    &::_Developer_default_instance_._instance,
};
const char descriptor_table_protodef_developer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017developer.proto\"\037\n\005Other\022\n\n\002v1\030\001 \001(\005\022\n"
    "\n\002v2\030\002 \001(\005\"\241\001\n\tDeveloper\022\014\n\004name\030\001 \001(\t\022\023"
    "\n\004week\030\002 \001(\0162\005.Week\022\014\n\004list\030\003 \003(\005\022 \n\003map"
    "\030\004 \003(\0132\023.Developer.MapEntry\022\025\n\005other\030\005 \001"
    "(\0132\006.Other\032*\n\010MapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v"
    "alue\030\002 \001(\005:\0028\001*E\n\004Week\022\007\n\003Mon\020\000\022\007\n\003Tue\020\003"
    "\022\007\n\003Wed\020\004\022\007\n\003Thu\020\005\022\007\n\003Fri\020\006\022\007\n\003Sat\020\007\022\007\n\003"
    "Sun\020\010b\006proto3"
};
static ::absl::once_flag descriptor_table_developer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_developer_2eproto = {
    false,
    false,
    293,
    descriptor_table_protodef_developer_2eproto,
    "developer.proto",
    &descriptor_table_developer_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_developer_2eproto::offsets,
    file_level_enum_descriptors_developer_2eproto,
    file_level_service_descriptors_developer_2eproto,
};
const ::google::protobuf::EnumDescriptor* Week_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_developer_2eproto);
  return file_level_enum_descriptors_developer_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Week_internal_data_[] = {
    65536u, 32u, 252u, };
bool Week_IsValid(int value) {
  return 0 <= value && value <= 8 && ((505u >> value) & 1) != 0;
}
// ===================================================================

class Other::_Internal {
 public:
};

Other::Other(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Other)
}
Other::Other(
    ::google::protobuf::Arena* arena, const Other& from)
    : Other(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Other::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Other::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, v1_),
           0,
           offsetof(Impl_, v2_) -
               offsetof(Impl_, v1_) +
               sizeof(Impl_::v2_));
}
Other::~Other() {
  // @@protoc_insertion_point(destructor:Other)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Other::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Other::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Other_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Other::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Other>(),
            ::google::protobuf::Message::GetNewImpl<Other>(),
            ::google::protobuf::Message::GetClearImpl<Other>(), &Other::ByteSizeLong,
                &Other::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Other, _impl_._cached_size_),
            false,
        },
        &Other::kDescriptorMethods,
        &descriptor_table_developer_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Other::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Other::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Other>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 v2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Other, _impl_.v2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Other, _impl_.v2_)}},
    // int32 v1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Other, _impl_.v1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Other, _impl_.v1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 v1 = 1;
    {PROTOBUF_FIELD_OFFSET(Other, _impl_.v1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 v2 = 2;
    {PROTOBUF_FIELD_OFFSET(Other, _impl_.v2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Other::Clear() {
// @@protoc_insertion_point(message_clear_start:Other)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.v1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.v2_) -
      reinterpret_cast<char*>(&_impl_.v1_)) + sizeof(_impl_.v2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Other::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Other& this_ = static_cast<const Other&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Other::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Other& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Other)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 v1 = 1;
          if (this_._internal_v1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_v1(), target);
          }

          // int32 v2 = 2;
          if (this_._internal_v2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_v2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Other)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Other::ByteSizeLong(const MessageLite& base) {
          const Other& this_ = static_cast<const Other&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Other::ByteSizeLong() const {
          const Other& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Other)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 v1 = 1;
            if (this_._internal_v1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_v1());
            }
            // int32 v2 = 2;
            if (this_._internal_v2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_v2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Other::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Other*>(&to_msg);
  auto& from = static_cast<const Other&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Other)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_v1() != 0) {
    _this->_impl_.v1_ = from._impl_.v1_;
  }
  if (from._internal_v2() != 0) {
    _this->_impl_.v2_ = from._impl_.v2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Other::CopyFrom(const Other& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Other)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Other::InternalSwap(Other* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Other, _impl_.v2_)
      + sizeof(Other::_impl_.v2_)
      - PROTOBUF_FIELD_OFFSET(Other, _impl_.v1_)>(
          reinterpret_cast<char*>(&_impl_.v1_),
          reinterpret_cast<char*>(&other->_impl_.v1_));
}

::google::protobuf::Metadata Other::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Developer_MapEntry_DoNotUse::Developer_MapEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Developer_MapEntry_DoNotUse::Developer_MapEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Developer_MapEntry_DoNotUse::Developer_MapEntry_DoNotUse() : SuperType() {}
              Developer_MapEntry_DoNotUse::Developer_MapEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  Developer_MapEntry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_Developer_MapEntry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &Developer_MapEntry_DoNotUse::MergeImpl,
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          ::google::protobuf::Message::GetDeleteImpl<Developer_MapEntry_DoNotUse>(),
                          ::google::protobuf::Message::GetNewImpl<Developer_MapEntry_DoNotUse>(),
                          ::google::protobuf::Message::ClearImpl, ::google::protobuf::Message::ByteSizeLongImpl,
                              ::google::protobuf::Message::_InternalSerializeImpl,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &Developer_MapEntry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_developer_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* Developer_MapEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> Developer_MapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Developer_MapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Developer_MapEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(Developer_MapEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\22\3\0\0\0\0\0\0"
    "Developer.MapEntry"
    "key"
  }},
};

// ===================================================================

class Developer::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Developer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Developer, _impl_._has_bits_);
};

Developer::Developer(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Developer)
}
inline PROTOBUF_NDEBUG_INLINE Developer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Developer& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        list_{visibility, arena, from.list_},
        _list_cached_byte_size_{0},
        map_{visibility, arena, from.map_},
        name_(arena, from.name_) {}

Developer::Developer(
    ::google::protobuf::Arena* arena,
    const Developer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Developer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.other_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Other>(
                              arena, *from._impl_.other_)
                        : nullptr;
  _impl_.week_ = from._impl_.week_;

  // @@protoc_insertion_point(copy_constructor:Developer)
}
inline PROTOBUF_NDEBUG_INLINE Developer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        list_{visibility, arena},
        _list_cached_byte_size_{0},
        map_{visibility, arena},
        name_(arena) {}

inline void Developer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, other_),
           0,
           offsetof(Impl_, week_) -
               offsetof(Impl_, other_) +
               sizeof(Impl_::week_));
}
Developer::~Developer() {
  // @@protoc_insertion_point(destructor:Developer)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Developer::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.other_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Developer::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Developer_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Developer::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Developer>(),
            ::google::protobuf::Message::GetNewImpl<Developer>(),
            ::google::protobuf::Message::GetClearImpl<Developer>(), &Developer::ByteSizeLong,
                &Developer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Developer, _impl_._cached_size_),
            false,
        },
        &Developer::kDescriptorMethods,
        &descriptor_table_developer_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Developer::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 25, 2> Developer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Developer, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Developer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Developer, _impl_.name_)}},
    // .Week week = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Developer, _impl_.week_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Developer, _impl_.week_)}},
    // repeated int32 list = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Developer, _impl_.list_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // .Other other = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(Developer, _impl_.other_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Developer, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Week week = 2;
    {PROTOBUF_FIELD_OFFSET(Developer, _impl_.week_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated int32 list = 3;
    {PROTOBUF_FIELD_OFFSET(Developer, _impl_.list_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // map<string, int32> map = 4;
    {PROTOBUF_FIELD_OFFSET(Developer, _impl_.map_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .Other other = 5;
    {PROTOBUF_FIELD_OFFSET(Developer, _impl_.other_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Other>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Developer()._impl_.map_)>(
        1, 0, 0, 9,
        5)},
  }}, {{
    "\11\4\0\0\3\0\0\0"
    "Developer"
    "name"
    "map"
  }},
};

PROTOBUF_NOINLINE void Developer::Clear() {
// @@protoc_insertion_point(message_clear_start:Developer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_.Clear();
  _impl_.map_.Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.other_ != nullptr);
    _impl_.other_->Clear();
  }
  _impl_.week_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Developer::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Developer& this_ = static_cast<const Developer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Developer::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Developer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Developer)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Developer.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .Week week = 2;
          if (this_._internal_week() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_week(), target);
          }

          // repeated int32 list = 3;
          {
            int byte_size = this_._impl_._list_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  3, this_._internal_list(), byte_size, target);
            }
          }

          // map<string, int32> map = 4;
          if (!this_._internal_map().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT32>;
            const auto& field = this_._internal_map();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Developer.map");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    4, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Developer.map");
              }
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Other other = 5;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.other_, this_._impl_.other_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Developer)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Developer::ByteSizeLong(const MessageLite& base) {
          const Developer& this_ = static_cast<const Developer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Developer::ByteSizeLong() const {
          const Developer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Developer)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 list = 3;
             {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_list())
              ;
              this_._impl_._list_cached_byte_size_.Set(
                  ::_pbi::ToCachedSize(data_size));
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
            // map<string, int32> map = 4;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_map_size());
              for (const auto& entry : this_._internal_map()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .Other other = 5;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.other_);
            }
          }
           {
            // .Week week = 2;
            if (this_._internal_week() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_week());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Developer::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Developer*>(&to_msg);
  auto& from = static_cast<const Developer&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Developer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_list()->MergeFrom(from._internal_list());
  _this->_impl_.map_.MergeFrom(from._impl_.map_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.other_ != nullptr);
    if (_this->_impl_.other_ == nullptr) {
      _this->_impl_.other_ =
          ::google::protobuf::Message::CopyConstruct<::Other>(arena, *from._impl_.other_);
    } else {
      _this->_impl_.other_->MergeFrom(*from._impl_.other_);
    }
  }
  if (from._internal_week() != 0) {
    _this->_impl_.week_ = from._impl_.week_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Developer::CopyFrom(const Developer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Developer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Developer::InternalSwap(Developer* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.list_.InternalSwap(&other->_impl_.list_);
  _impl_.map_.InternalSwap(&other->_impl_.map_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Developer, _impl_.week_)
      + sizeof(Developer::_impl_.week_)
      - PROTOBUF_FIELD_OFFSET(Developer, _impl_.other_)>(
          reinterpret_cast<char*>(&_impl_.other_),
          reinterpret_cast<char*>(&other->_impl_.other_));
}

::google::protobuf::Metadata Developer::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_developer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
