// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: developer.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_developer_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_developer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_developer_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_developer_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_developer_2eproto;
class Developer;
struct DeveloperDefaultTypeInternal;
extern DeveloperDefaultTypeInternal _Developer_default_instance_;
class Developer_MapEntry_DoNotUse;
struct Developer_MapEntry_DoNotUseDefaultTypeInternal;
extern Developer_MapEntry_DoNotUseDefaultTypeInternal _Developer_MapEntry_DoNotUse_default_instance_;
class Other;
struct OtherDefaultTypeInternal;
extern OtherDefaultTypeInternal _Other_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum Week : int {
  Mon = 0,
  Tue = 3,
  Wed = 4,
  Thu = 5,
  Fri = 6,
  Sat = 7,
  Sun = 8,
  Week_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  Week_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool Week_IsValid(int value);
extern const uint32_t Week_internal_data_[];
constexpr Week Week_MIN = static_cast<Week>(0);
constexpr Week Week_MAX = static_cast<Week>(8);
constexpr int Week_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor*
Week_descriptor();
template <typename T>
const std::string& Week_Name(T value) {
  static_assert(std::is_same<T, Week>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Week_Name().");
  return Week_Name(static_cast<Week>(value));
}
template <>
inline const std::string& Week_Name(Week value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Week_descriptor,
                                                 0, 8>(
      static_cast<int>(value));
}
inline bool Week_Parse(absl::string_view name, Week* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Week>(
      Week_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Other final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Other) */ {
 public:
  inline Other() : Other(nullptr) {}
  ~Other() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Other(
      ::google::protobuf::internal::ConstantInitialized);

  inline Other(const Other& from) : Other(nullptr, from) {}
  inline Other(Other&& from) noexcept
      : Other(nullptr, std::move(from)) {}
  inline Other& operator=(const Other& from) {
    CopyFrom(from);
    return *this;
  }
  inline Other& operator=(Other&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Other& default_instance() {
    return *internal_default_instance();
  }
  static inline const Other* internal_default_instance() {
    return reinterpret_cast<const Other*>(
        &_Other_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Other& a, Other& b) { a.Swap(&b); }
  inline void Swap(Other* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Other* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Other* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Other>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Other& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Other& from) { Other::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Other* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Other"; }

 protected:
  explicit Other(::google::protobuf::Arena* arena);
  Other(::google::protobuf::Arena* arena, const Other& from);
  Other(::google::protobuf::Arena* arena, Other&& from) noexcept
      : Other(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kV1FieldNumber = 1,
    kV2FieldNumber = 2,
  };
  // int32 v1 = 1;
  void clear_v1() ;
  ::int32_t v1() const;
  void set_v1(::int32_t value);

  private:
  ::int32_t _internal_v1() const;
  void _internal_set_v1(::int32_t value);

  public:
  // int32 v2 = 2;
  void clear_v2() ;
  ::int32_t v2() const;
  void set_v2(::int32_t value);

  private:
  ::int32_t _internal_v2() const;
  void _internal_set_v2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Other)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Other_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Other& from_msg);
    ::int32_t v1_;
    ::int32_t v2_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_developer_2eproto;
};
// -------------------------------------------------------------------

class Developer_MapEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          Developer_MapEntry_DoNotUse, std::string, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      Developer_MapEntry_DoNotUse, std::string, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  Developer_MapEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Developer_MapEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Developer_MapEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Developer_MapEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Developer_MapEntry_DoNotUse*>(
        &_Developer_MapEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      30, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_developer_2eproto;
};
// -------------------------------------------------------------------

class Developer final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Developer) */ {
 public:
  inline Developer() : Developer(nullptr) {}
  ~Developer() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Developer(
      ::google::protobuf::internal::ConstantInitialized);

  inline Developer(const Developer& from) : Developer(nullptr, from) {}
  inline Developer(Developer&& from) noexcept
      : Developer(nullptr, std::move(from)) {}
  inline Developer& operator=(const Developer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Developer& operator=(Developer&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Developer& default_instance() {
    return *internal_default_instance();
  }
  static inline const Developer* internal_default_instance() {
    return reinterpret_cast<const Developer*>(
        &_Developer_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Developer& a, Developer& b) { a.Swap(&b); }
  inline void Swap(Developer* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Developer* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Developer* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Developer>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Developer& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Developer& from) { Developer::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Developer* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Developer"; }

 protected:
  explicit Developer(::google::protobuf::Arena* arena);
  Developer(::google::protobuf::Arena* arena, const Developer& from);
  Developer(::google::protobuf::Arena* arena, Developer&& from) noexcept
      : Developer(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kListFieldNumber = 3,
    kMapFieldNumber = 4,
    kNameFieldNumber = 1,
    kOtherFieldNumber = 5,
    kWeekFieldNumber = 2,
  };
  // repeated int32 list = 3;
  int list_size() const;
  private:
  int _internal_list_size() const;

  public:
  void clear_list() ;
  ::int32_t list(int index) const;
  void set_list(int index, ::int32_t value);
  void add_list(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& list() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_list();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_list() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_list();

  public:
  // map<string, int32> map = 4;
  int map_size() const;
  private:
  int _internal_map_size() const;

  public:
  void clear_map() ;
  const ::google::protobuf::Map<std::string, ::int32_t>& map() const;
  ::google::protobuf::Map<std::string, ::int32_t>* mutable_map();

  private:
  const ::google::protobuf::Map<std::string, ::int32_t>& _internal_map() const;
  ::google::protobuf::Map<std::string, ::int32_t>* _internal_mutable_map();

  public:
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .Other other = 5;
  bool has_other() const;
  void clear_other() ;
  const ::Other& other() const;
  PROTOBUF_NODISCARD ::Other* release_other();
  ::Other* mutable_other();
  void set_allocated_other(::Other* value);
  void unsafe_arena_set_allocated_other(::Other* value);
  ::Other* unsafe_arena_release_other();

  private:
  const ::Other& _internal_other() const;
  ::Other* _internal_mutable_other();

  public:
  // .Week week = 2;
  void clear_week() ;
  ::Week week() const;
  void set_week(::Week value);

  private:
  ::Week _internal_week() const;
  void _internal_set_week(::Week value);

  public:
  // @@protoc_insertion_point(class_scope:Developer)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      25, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Developer_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Developer& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> list_;
    mutable ::google::protobuf::internal::CachedSize _list_cached_byte_size_;
    ::google::protobuf::internal::MapField<Developer_MapEntry_DoNotUse, std::string, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        map_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::Other* other_;
    int week_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_developer_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Other

// int32 v1 = 1;
inline void Other::clear_v1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v1_ = 0;
}
inline ::int32_t Other::v1() const {
  // @@protoc_insertion_point(field_get:Other.v1)
  return _internal_v1();
}
inline void Other::set_v1(::int32_t value) {
  _internal_set_v1(value);
  // @@protoc_insertion_point(field_set:Other.v1)
}
inline ::int32_t Other::_internal_v1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v1_;
}
inline void Other::_internal_set_v1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v1_ = value;
}

// int32 v2 = 2;
inline void Other::clear_v2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v2_ = 0;
}
inline ::int32_t Other::v2() const {
  // @@protoc_insertion_point(field_get:Other.v2)
  return _internal_v2();
}
inline void Other::set_v2(::int32_t value) {
  _internal_set_v2(value);
  // @@protoc_insertion_point(field_set:Other.v2)
}
inline ::int32_t Other::_internal_v2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v2_;
}
inline void Other::_internal_set_v2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v2_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Developer

// string name = 1;
inline void Developer::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Developer::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Developer.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Developer::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Developer.name)
}
inline std::string* Developer::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Developer.name)
  return _s;
}
inline const std::string& Developer::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Developer::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Developer::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Developer::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Developer.name)
  return _impl_.name_.Release();
}
inline void Developer::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Developer.name)
}

// .Week week = 2;
inline void Developer::clear_week() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.week_ = 0;
}
inline ::Week Developer::week() const {
  // @@protoc_insertion_point(field_get:Developer.week)
  return _internal_week();
}
inline void Developer::set_week(::Week value) {
  _internal_set_week(value);
  // @@protoc_insertion_point(field_set:Developer.week)
}
inline ::Week Developer::_internal_week() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Week>(_impl_.week_);
}
inline void Developer::_internal_set_week(::Week value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.week_ = value;
}

// repeated int32 list = 3;
inline int Developer::_internal_list_size() const {
  return _internal_list().size();
}
inline int Developer::list_size() const {
  return _internal_list_size();
}
inline void Developer::clear_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_.Clear();
}
inline ::int32_t Developer::list(int index) const {
  // @@protoc_insertion_point(field_get:Developer.list)
  return _internal_list().Get(index);
}
inline void Developer::set_list(int index, ::int32_t value) {
  _internal_mutable_list()->Set(index, value);
  // @@protoc_insertion_point(field_set:Developer.list)
}
inline void Developer::add_list(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_list()->Add(value);
  // @@protoc_insertion_point(field_add:Developer.list)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Developer::list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Developer.list)
  return _internal_list();
}
inline ::google::protobuf::RepeatedField<::int32_t>* Developer::mutable_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Developer.list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_list();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Developer::_internal_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* Developer::_internal_mutable_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.list_;
}

// map<string, int32> map = 4;
inline int Developer::_internal_map_size() const {
  return _internal_map().size();
}
inline int Developer::map_size() const {
  return _internal_map_size();
}
inline void Developer::clear_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Developer::_internal_map() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.map_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Developer::map() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Developer.map)
  return _internal_map();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Developer::_internal_mutable_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.map_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Developer::mutable_map() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Developer.map)
  return _internal_mutable_map();
}

// .Other other = 5;
inline bool Developer::has_other() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.other_ != nullptr);
  return value;
}
inline void Developer::clear_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.other_ != nullptr) _impl_.other_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Other& Developer::_internal_other() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Other* p = _impl_.other_;
  return p != nullptr ? *p : reinterpret_cast<const ::Other&>(::_Other_default_instance_);
}
inline const ::Other& Developer::other() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Developer.other)
  return _internal_other();
}
inline void Developer::unsafe_arena_set_allocated_other(::Other* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.other_);
  }
  _impl_.other_ = reinterpret_cast<::Other*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Developer.other)
}
inline ::Other* Developer::release_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Other* released = _impl_.other_;
  _impl_.other_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Other* Developer::unsafe_arena_release_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Developer.other)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Other* temp = _impl_.other_;
  _impl_.other_ = nullptr;
  return temp;
}
inline ::Other* Developer::_internal_mutable_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.other_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Other>(GetArena());
    _impl_.other_ = reinterpret_cast<::Other*>(p);
  }
  return _impl_.other_;
}
inline ::Other* Developer::mutable_other() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Other* _msg = _internal_mutable_other();
  // @@protoc_insertion_point(field_mutable:Developer.other)
  return _msg;
}
inline void Developer::set_allocated_other(::Other* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.other_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.other_ = reinterpret_cast<::Other*>(value);
  // @@protoc_insertion_point(field_set_allocated:Developer.other)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Week> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Week>() {
  return ::Week_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_developer_2eproto_2epb_2eh
