// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf C++ Version: 5.28.3

#include "employee.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Employee::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        salary_{0},
        age_{0},
        gender_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Employee::Employee(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EmployeeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmployeeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmployeeDefaultTypeInternal() {}
  union {
    Employee _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmployeeDefaultTypeInternal _Employee_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_employee_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_employee_2eproto = nullptr;
const ::uint32_t
    TableStruct_employee_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Employee, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.age_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.salary_),
        PROTOBUF_FIELD_OFFSET(::Employee, _impl_.gender_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Employee)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Employee_default_instance_._instance,
};
const char descriptor_table_protodef_employee_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016employee.proto\"E\n\010Employee\022\014\n\004name\030\001 \001"
    "(\t\022\013\n\003age\030\002 \001(\005\022\016\n\006salary\030\003 \001(\001\022\016\n\006gende"
    "r\030\004 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_employee_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_employee_2eproto = {
    false,
    false,
    95,
    descriptor_table_protodef_employee_2eproto,
    "employee.proto",
    &descriptor_table_employee_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_employee_2eproto::offsets,
    file_level_enum_descriptors_employee_2eproto,
    file_level_service_descriptors_employee_2eproto,
};
// ===================================================================

class Employee::_Internal {
 public:
};

Employee::Employee(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Employee& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Employee::Employee(
    ::google::protobuf::Arena* arena,
    const Employee& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Employee* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, salary_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, salary_),
           offsetof(Impl_, gender_) -
               offsetof(Impl_, salary_) +
               sizeof(Impl_::gender_));

  // @@protoc_insertion_point(copy_constructor:Employee)
}
inline PROTOBUF_NDEBUG_INLINE Employee::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Employee::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, salary_),
           0,
           offsetof(Impl_, gender_) -
               offsetof(Impl_, salary_) +
               sizeof(Impl_::gender_));
}
Employee::~Employee() {
  // @@protoc_insertion_point(destructor:Employee)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Employee::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Employee::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Employee_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Employee::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Employee>(),
            ::google::protobuf::Message::GetNewImpl<Employee>(),
            ::google::protobuf::Message::GetClearImpl<Employee>(), &Employee::ByteSizeLong,
                &Employee::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Employee, _impl_._cached_size_),
            false,
        },
        &Employee::kDescriptorMethods,
        &descriptor_table_employee_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Employee::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 21, 2> Employee::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Employee>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool gender = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Employee, _impl_.gender_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.gender_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.name_)}},
    // int32 age = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Employee, _impl_.age_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.age_)}},
    // double salary = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Employee, _impl_.salary_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 age = 2;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.age_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double salary = 3;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.salary_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // bool gender = 4;
    {PROTOBUF_FIELD_OFFSET(Employee, _impl_.gender_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\10\4\0\0\0\0\0\0"
    "Employee"
    "name"
  }},
};

PROTOBUF_NOINLINE void Employee::Clear() {
// @@protoc_insertion_point(message_clear_start:Employee)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.salary_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.gender_) -
      reinterpret_cast<char*>(&_impl_.salary_)) + sizeof(_impl_.gender_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Employee::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Employee& this_ = static_cast<const Employee&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Employee::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Employee& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Employee)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Employee.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 age = 2;
          if (this_._internal_age() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_age(), target);
          }

          // double salary = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_salary()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_salary(), target);
          }

          // bool gender = 4;
          if (this_._internal_gender() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_gender(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Employee)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Employee::ByteSizeLong(const MessageLite& base) {
          const Employee& this_ = static_cast<const Employee&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Employee::ByteSizeLong() const {
          const Employee& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Employee)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // double salary = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_salary()) != 0) {
              total_size += 9;
            }
            // int32 age = 2;
            if (this_._internal_age() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_age());
            }
            // bool gender = 4;
            if (this_._internal_gender() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Employee::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Employee*>(&to_msg);
  auto& from = static_cast<const Employee&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Employee)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_salary()) != 0) {
    _this->_impl_.salary_ = from._impl_.salary_;
  }
  if (from._internal_age() != 0) {
    _this->_impl_.age_ = from._impl_.age_;
  }
  if (from._internal_gender() != 0) {
    _this->_impl_.gender_ = from._impl_.gender_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Employee::CopyFrom(const Employee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Employee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Employee::InternalSwap(Employee* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Employee, _impl_.gender_)
      + sizeof(Employee::_impl_.gender_)
      - PROTOBUF_FIELD_OFFSET(Employee, _impl_.salary_)>(
          reinterpret_cast<char*>(&_impl_.salary_),
          reinterpret_cast<char*>(&other->_impl_.salary_));
}

::google::protobuf::Metadata Employee::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_employee_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
