// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nested.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_nested_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_nested_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_nested_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_nested_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_nested_2eproto;
class Nested;
struct NestedDefaultTypeInternal;
extern NestedDefaultTypeInternal _Nested_default_instance_;
class Nested_Other;
struct Nested_OtherDefaultTypeInternal;
extern Nested_OtherDefaultTypeInternal _Nested_Other_default_instance_;
class Nested_TelesEntry_DoNotUse;
struct Nested_TelesEntry_DoNotUseDefaultTypeInternal;
extern Nested_TelesEntry_DoNotUseDefaultTypeInternal _Nested_TelesEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Nested_TelesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          Nested_TelesEntry_DoNotUse, std::string, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      Nested_TelesEntry_DoNotUse, std::string, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  Nested_TelesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Nested_TelesEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Nested_TelesEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Nested_TelesEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Nested_TelesEntry_DoNotUse*>(
        &_Nested_TelesEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      29, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_nested_2eproto;
};
// -------------------------------------------------------------------

class Nested_Other final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nested.Other) */ {
 public:
  inline Nested_Other() : Nested_Other(nullptr) {}
  ~Nested_Other() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Nested_Other(
      ::google::protobuf::internal::ConstantInitialized);

  inline Nested_Other(const Nested_Other& from) : Nested_Other(nullptr, from) {}
  inline Nested_Other(Nested_Other&& from) noexcept
      : Nested_Other(nullptr, std::move(from)) {}
  inline Nested_Other& operator=(const Nested_Other& from) {
    CopyFrom(from);
    return *this;
  }
  inline Nested_Other& operator=(Nested_Other&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Nested_Other& default_instance() {
    return *internal_default_instance();
  }
  static inline const Nested_Other* internal_default_instance() {
    return reinterpret_cast<const Nested_Other*>(
        &_Nested_Other_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Nested_Other& a, Nested_Other& b) { a.Swap(&b); }
  inline void Swap(Nested_Other* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Nested_Other* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Nested_Other* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Nested_Other>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Nested_Other& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Nested_Other& from) { Nested_Other::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Nested_Other* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Nested.Other"; }

 protected:
  explicit Nested_Other(::google::protobuf::Arena* arena);
  Nested_Other(::google::protobuf::Arena* arena, const Nested_Other& from);
  Nested_Other(::google::protobuf::Arena* arena, Nested_Other&& from) noexcept
      : Nested_Other(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kV1FieldNumber = 1,
    kV2FieldNumber = 2,
  };
  // int32 v1 = 1;
  void clear_v1() ;
  ::int32_t v1() const;
  void set_v1(::int32_t value);

  private:
  ::int32_t _internal_v1() const;
  void _internal_set_v1(::int32_t value);

  public:
  // int32 v2 = 2;
  void clear_v2() ;
  ::int32_t v2() const;
  void set_v2(::int32_t value);

  private:
  ::int32_t _internal_v2() const;
  void _internal_set_v2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Nested.Other)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Nested_Other_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Nested_Other& from_msg);
    ::int32_t v1_;
    ::int32_t v2_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nested_2eproto;
};
// -------------------------------------------------------------------

class Nested final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Nested) */ {
 public:
  inline Nested() : Nested(nullptr) {}
  ~Nested() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Nested(
      ::google::protobuf::internal::ConstantInitialized);

  inline Nested(const Nested& from) : Nested(nullptr, from) {}
  inline Nested(Nested&& from) noexcept
      : Nested(nullptr, std::move(from)) {}
  inline Nested& operator=(const Nested& from) {
    CopyFrom(from);
    return *this;
  }
  inline Nested& operator=(Nested&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Nested& default_instance() {
    return *internal_default_instance();
  }
  static inline const Nested* internal_default_instance() {
    return reinterpret_cast<const Nested*>(
        &_Nested_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Nested& a, Nested& b) { a.Swap(&b); }
  inline void Swap(Nested* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Nested* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Nested* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Nested>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Nested& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Nested& from) { Nested::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Nested* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Nested"; }

 protected:
  explicit Nested(::google::protobuf::Arena* arena);
  Nested(::google::protobuf::Arena* arena, const Nested& from);
  Nested(::google::protobuf::Arena* arena, Nested&& from) noexcept
      : Nested(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Other = Nested_Other;

  // accessors -------------------------------------------------------
  enum : int {
    kTelesFieldNumber = 2,
    kNameFieldNumber = 1,
    kOtherFieldNumber = 3,
  };
  // map<string, int32> teles = 2;
  int teles_size() const;
  private:
  int _internal_teles_size() const;

  public:
  void clear_teles() ;
  const ::google::protobuf::Map<std::string, ::int32_t>& teles() const;
  ::google::protobuf::Map<std::string, ::int32_t>* mutable_teles();

  private:
  const ::google::protobuf::Map<std::string, ::int32_t>& _internal_teles() const;
  ::google::protobuf::Map<std::string, ::int32_t>* _internal_mutable_teles();

  public:
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .Nested.Other other = 3;
  bool has_other() const;
  void clear_other() ;
  const ::Nested_Other& other() const;
  PROTOBUF_NODISCARD ::Nested_Other* release_other();
  ::Nested_Other* mutable_other();
  void set_allocated_other(::Nested_Other* value);
  void unsafe_arena_set_allocated_other(::Nested_Other* value);
  ::Nested_Other* unsafe_arena_release_other();

  private:
  const ::Nested_Other& _internal_other() const;
  ::Nested_Other* _internal_mutable_other();

  public:
  // @@protoc_insertion_point(class_scope:Nested)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      24, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Nested_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Nested& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<Nested_TelesEntry_DoNotUse, std::string, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        teles_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::Nested_Other* other_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_nested_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Nested_Other

// int32 v1 = 1;
inline void Nested_Other::clear_v1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v1_ = 0;
}
inline ::int32_t Nested_Other::v1() const {
  // @@protoc_insertion_point(field_get:Nested.Other.v1)
  return _internal_v1();
}
inline void Nested_Other::set_v1(::int32_t value) {
  _internal_set_v1(value);
  // @@protoc_insertion_point(field_set:Nested.Other.v1)
}
inline ::int32_t Nested_Other::_internal_v1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v1_;
}
inline void Nested_Other::_internal_set_v1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v1_ = value;
}

// int32 v2 = 2;
inline void Nested_Other::clear_v2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v2_ = 0;
}
inline ::int32_t Nested_Other::v2() const {
  // @@protoc_insertion_point(field_get:Nested.Other.v2)
  return _internal_v2();
}
inline void Nested_Other::set_v2(::int32_t value) {
  _internal_set_v2(value);
  // @@protoc_insertion_point(field_set:Nested.Other.v2)
}
inline ::int32_t Nested_Other::_internal_v2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.v2_;
}
inline void Nested_Other::_internal_set_v2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.v2_ = value;
}

// -------------------------------------------------------------------

// Nested

// string name = 1;
inline void Nested::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Nested::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nested.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Nested::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Nested.name)
}
inline std::string* Nested::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Nested.name)
  return _s;
}
inline const std::string& Nested::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Nested::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Nested::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Nested::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nested.name)
  return _impl_.name_.Release();
}
inline void Nested::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nested.name)
}

// map<string, int32> teles = 2;
inline int Nested::_internal_teles_size() const {
  return _internal_teles().size();
}
inline int Nested::teles_size() const {
  return _internal_teles_size();
}
inline void Nested::clear_teles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.teles_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Nested::_internal_teles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.teles_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Nested::teles() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Nested.teles)
  return _internal_teles();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Nested::_internal_mutable_teles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.teles_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Nested::mutable_teles() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Nested.teles)
  return _internal_mutable_teles();
}

// .Nested.Other other = 3;
inline bool Nested::has_other() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.other_ != nullptr);
  return value;
}
inline void Nested::clear_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.other_ != nullptr) _impl_.other_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Nested_Other& Nested::_internal_other() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Nested_Other* p = _impl_.other_;
  return p != nullptr ? *p : reinterpret_cast<const ::Nested_Other&>(::_Nested_Other_default_instance_);
}
inline const ::Nested_Other& Nested::other() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Nested.other)
  return _internal_other();
}
inline void Nested::unsafe_arena_set_allocated_other(::Nested_Other* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.other_);
  }
  _impl_.other_ = reinterpret_cast<::Nested_Other*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Nested.other)
}
inline ::Nested_Other* Nested::release_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Nested_Other* released = _impl_.other_;
  _impl_.other_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Nested_Other* Nested::unsafe_arena_release_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Nested.other)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Nested_Other* temp = _impl_.other_;
  _impl_.other_ = nullptr;
  return temp;
}
inline ::Nested_Other* Nested::_internal_mutable_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.other_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Nested_Other>(GetArena());
    _impl_.other_ = reinterpret_cast<::Nested_Other*>(p);
  }
  return _impl_.other_;
}
inline ::Nested_Other* Nested::mutable_other() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Nested_Other* _msg = _internal_mutable_other();
  // @@protoc_insertion_point(field_mutable:Nested.other)
  return _msg;
}
inline void Nested::set_allocated_other(::Nested_Other* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.other_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.other_ = reinterpret_cast<::Nested_Other*>(value);
  // @@protoc_insertion_point(field_set_allocated:Nested.other)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_nested_2eproto_2epb_2eh
