// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nested.proto
// Protobuf C++ Version: 5.28.3

#include "nested.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
              template <typename>
PROTOBUF_CONSTEXPR Nested_TelesEntry_DoNotUse::Nested_TelesEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Nested_TelesEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Nested_TelesEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Nested_TelesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Nested_TelesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Nested_TelesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Nested_TelesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Nested_TelesEntry_DoNotUseDefaultTypeInternal _Nested_TelesEntry_DoNotUse_default_instance_;

inline constexpr Nested_Other::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : v1_{0},
        v2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Nested_Other::Nested_Other(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Nested_OtherDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Nested_OtherDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Nested_OtherDefaultTypeInternal() {}
  union {
    Nested_Other _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Nested_OtherDefaultTypeInternal _Nested_Other_default_instance_;

inline constexpr Nested::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        teles_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        other_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Nested::Nested(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NestedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NestedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NestedDefaultTypeInternal() {}
  union {
    Nested _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NestedDefaultTypeInternal _Nested_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_nested_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_nested_2eproto = nullptr;
const ::uint32_t
    TableStruct_nested_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Nested_TelesEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Nested_TelesEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nested_TelesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Nested_TelesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Nested_Other, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nested_Other, _impl_.v1_),
        PROTOBUF_FIELD_OFFSET(::Nested_Other, _impl_.v2_),
        PROTOBUF_FIELD_OFFSET(::Nested, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Nested, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Nested, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Nested, _impl_.teles_),
        PROTOBUF_FIELD_OFFSET(::Nested, _impl_.other_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::Nested_TelesEntry_DoNotUse)},
        {12, -1, -1, sizeof(::Nested_Other)},
        {22, 33, -1, sizeof(::Nested)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Nested_TelesEntry_DoNotUse_default_instance_._instance,
    &::_Nested_Other_default_instance_._instance,
    &::_Nested_default_instance_._instance,
};
const char descriptor_table_protodef_nested_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014nested.proto\"\246\001\n\006Nested\022\014\n\004name\030\001 \001(\t\022"
    "!\n\005teles\030\002 \003(\0132\022.Nested.TelesEntry\022\034\n\005ot"
    "her\030\003 \001(\0132\r.Nested.Other\032,\n\nTelesEntry\022\013"
    "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\032\037\n\005Other\022"
    "\n\n\002v1\030\001 \001(\005\022\n\n\002v2\030\002 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_nested_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nested_2eproto = {
    false,
    false,
    191,
    descriptor_table_protodef_nested_2eproto,
    "nested.proto",
    &descriptor_table_nested_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_nested_2eproto::offsets,
    file_level_enum_descriptors_nested_2eproto,
    file_level_service_descriptors_nested_2eproto,
};
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Nested_TelesEntry_DoNotUse::Nested_TelesEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Nested_TelesEntry_DoNotUse::Nested_TelesEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Nested_TelesEntry_DoNotUse::Nested_TelesEntry_DoNotUse() : SuperType() {}
              Nested_TelesEntry_DoNotUse::Nested_TelesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  Nested_TelesEntry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_Nested_TelesEntry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &Nested_TelesEntry_DoNotUse::MergeImpl,
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          ::google::protobuf::Message::GetDeleteImpl<Nested_TelesEntry_DoNotUse>(),
                          ::google::protobuf::Message::GetNewImpl<Nested_TelesEntry_DoNotUse>(),
                          ::google::protobuf::Message::ClearImpl, ::google::protobuf::Message::ByteSizeLongImpl,
                              ::google::protobuf::Message::_InternalSerializeImpl,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &Nested_TelesEntry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_nested_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* Nested_TelesEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> Nested_TelesEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nested_TelesEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Nested_TelesEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(Nested_TelesEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\3\0\0\0\0\0\0"
    "Nested.TelesEntry"
    "key"
  }},
};

// ===================================================================

class Nested_Other::_Internal {
 public:
};

Nested_Other::Nested_Other(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nested.Other)
}
Nested_Other::Nested_Other(
    ::google::protobuf::Arena* arena, const Nested_Other& from)
    : Nested_Other(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Nested_Other::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Nested_Other::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, v1_),
           0,
           offsetof(Impl_, v2_) -
               offsetof(Impl_, v1_) +
               sizeof(Impl_::v2_));
}
Nested_Other::~Nested_Other() {
  // @@protoc_insertion_point(destructor:Nested.Other)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Nested_Other::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Nested_Other::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Nested_Other_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Nested_Other::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Nested_Other>(),
            ::google::protobuf::Message::GetNewImpl<Nested_Other>(),
            ::google::protobuf::Message::GetClearImpl<Nested_Other>(), &Nested_Other::ByteSizeLong,
                &Nested_Other::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_._cached_size_),
            false,
        },
        &Nested_Other::kDescriptorMethods,
        &descriptor_table_nested_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Nested_Other::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Nested_Other::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nested_Other>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 v2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Nested_Other, _impl_.v2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v2_)}},
    // int32 v1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Nested_Other, _impl_.v1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 v1 = 1;
    {PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 v2 = 2;
    {PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Nested_Other::Clear() {
// @@protoc_insertion_point(message_clear_start:Nested.Other)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.v1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.v2_) -
      reinterpret_cast<char*>(&_impl_.v1_)) + sizeof(_impl_.v2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Nested_Other::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Nested_Other& this_ = static_cast<const Nested_Other&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Nested_Other::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Nested_Other& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Nested.Other)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 v1 = 1;
          if (this_._internal_v1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_v1(), target);
          }

          // int32 v2 = 2;
          if (this_._internal_v2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_v2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Nested.Other)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Nested_Other::ByteSizeLong(const MessageLite& base) {
          const Nested_Other& this_ = static_cast<const Nested_Other&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Nested_Other::ByteSizeLong() const {
          const Nested_Other& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Nested.Other)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 v1 = 1;
            if (this_._internal_v1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_v1());
            }
            // int32 v2 = 2;
            if (this_._internal_v2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_v2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Nested_Other::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Nested_Other*>(&to_msg);
  auto& from = static_cast<const Nested_Other&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nested.Other)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_v1() != 0) {
    _this->_impl_.v1_ = from._impl_.v1_;
  }
  if (from._internal_v2() != 0) {
    _this->_impl_.v2_ = from._impl_.v2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Nested_Other::CopyFrom(const Nested_Other& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nested.Other)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Nested_Other::InternalSwap(Nested_Other* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v2_)
      + sizeof(Nested_Other::_impl_.v2_)
      - PROTOBUF_FIELD_OFFSET(Nested_Other, _impl_.v1_)>(
          reinterpret_cast<char*>(&_impl_.v1_),
          reinterpret_cast<char*>(&other->_impl_.v1_));
}

::google::protobuf::Metadata Nested_Other::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Nested::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Nested>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Nested, _impl_._has_bits_);
};

Nested::Nested(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nested)
}
inline PROTOBUF_NDEBUG_INLINE Nested::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Nested& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        teles_{visibility, arena, from.teles_},
        name_(arena, from.name_) {}

Nested::Nested(
    ::google::protobuf::Arena* arena,
    const Nested& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Nested* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.other_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Nested_Other>(
                              arena, *from._impl_.other_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Nested)
}
inline PROTOBUF_NDEBUG_INLINE Nested::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        teles_{visibility, arena},
        name_(arena) {}

inline void Nested::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.other_ = {};
}
Nested::~Nested() {
  // @@protoc_insertion_point(destructor:Nested)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Nested::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.other_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Nested::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Nested_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Nested::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Nested>(),
            ::google::protobuf::Message::GetNewImpl<Nested>(),
            ::google::protobuf::Message::GetClearImpl<Nested>(), &Nested::ByteSizeLong,
                &Nested::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Nested, _impl_._cached_size_),
            false,
        },
        &Nested::kDescriptorMethods,
        &descriptor_table_nested_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Nested::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 24, 2> Nested::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Nested, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Nested>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Nested, _impl_.name_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // .Nested.Other other = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(Nested, _impl_.other_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Nested, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<string, int32> teles = 2;
    {PROTOBUF_FIELD_OFFSET(Nested, _impl_.teles_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .Nested.Other other = 3;
    {PROTOBUF_FIELD_OFFSET(Nested, _impl_.other_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Nested_Other>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Nested()._impl_.teles_)>(
        1, 0, 0, 9,
        5)},
  }}, {{
    "\6\4\5\0\0\0\0\0"
    "Nested"
    "name"
    "teles"
  }},
};

PROTOBUF_NOINLINE void Nested::Clear() {
// @@protoc_insertion_point(message_clear_start:Nested)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.teles_.Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.other_ != nullptr);
    _impl_.other_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Nested::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Nested& this_ = static_cast<const Nested&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Nested::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Nested& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Nested)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nested.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // map<string, int32> teles = 2;
          if (!this_._internal_teles().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT32>;
            const auto& field = this_._internal_teles();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nested.teles");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Nested.teles");
              }
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Nested.Other other = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.other_, this_._impl_.other_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Nested)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Nested::ByteSizeLong(const MessageLite& base) {
          const Nested& this_ = static_cast<const Nested&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Nested::ByteSizeLong() const {
          const Nested& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Nested)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, int32> teles = 2;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_teles_size());
              for (const auto& entry : this_._internal_teles()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .Nested.Other other = 3;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.other_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Nested::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Nested*>(&to_msg);
  auto& from = static_cast<const Nested&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Nested)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.teles_.MergeFrom(from._impl_.teles_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.other_ != nullptr);
    if (_this->_impl_.other_ == nullptr) {
      _this->_impl_.other_ =
          ::google::protobuf::Message::CopyConstruct<::Nested_Other>(arena, *from._impl_.other_);
    } else {
      _this->_impl_.other_->MergeFrom(*from._impl_.other_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Nested::CopyFrom(const Nested& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nested)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Nested::InternalSwap(Nested* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.teles_.InternalSwap(&other->_impl_.teles_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.other_, other->_impl_.other_);
}

::google::protobuf::Metadata Nested::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_nested_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
