// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: specialist.proto
// Protobuf C++ Version: 5.28.3

#include "specialist.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Specialist::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        employee_{nullptr},
        age_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Specialist::Specialist(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SpecialistDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpecialistDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpecialistDefaultTypeInternal() {}
  union {
    Specialist _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpecialistDefaultTypeInternal _Specialist_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_specialist_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_specialist_2eproto = nullptr;
const ::uint32_t
    TableStruct_specialist_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Specialist, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Specialist, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Specialist, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Specialist, _impl_.age_),
        PROTOBUF_FIELD_OFFSET(::Specialist, _impl_.employee_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::Specialist)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Specialist_default_instance_._instance,
};
const char descriptor_table_protodef_specialist_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020specialist.proto\032\016employee.proto\"D\n\nSp"
    "ecialist\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\033\n\010e"
    "mployee\030\003 \001(\0132\t.Employeeb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_specialist_2eproto_deps[1] =
    {
        &::descriptor_table_employee_2eproto,
};
static ::absl::once_flag descriptor_table_specialist_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_specialist_2eproto = {
    false,
    false,
    112,
    descriptor_table_protodef_specialist_2eproto,
    "specialist.proto",
    &descriptor_table_specialist_2eproto_once,
    descriptor_table_specialist_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_specialist_2eproto::offsets,
    file_level_enum_descriptors_specialist_2eproto,
    file_level_service_descriptors_specialist_2eproto,
};
// ===================================================================

class Specialist::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Specialist>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Specialist, _impl_._has_bits_);
};

void Specialist::clear_employee() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.employee_ != nullptr) _impl_.employee_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Specialist::Specialist(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Specialist)
}
inline PROTOBUF_NDEBUG_INLINE Specialist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Specialist& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

Specialist::Specialist(
    ::google::protobuf::Arena* arena,
    const Specialist& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Specialist* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.employee_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Employee>(
                              arena, *from._impl_.employee_)
                        : nullptr;
  _impl_.age_ = from._impl_.age_;

  // @@protoc_insertion_point(copy_constructor:Specialist)
}
inline PROTOBUF_NDEBUG_INLINE Specialist::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void Specialist::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, employee_),
           0,
           offsetof(Impl_, age_) -
               offsetof(Impl_, employee_) +
               sizeof(Impl_::age_));
}
Specialist::~Specialist() {
  // @@protoc_insertion_point(destructor:Specialist)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Specialist::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.employee_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Specialist::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Specialist_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Specialist::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Specialist>(),
            ::google::protobuf::Message::GetNewImpl<Specialist>(),
            ::google::protobuf::Message::GetClearImpl<Specialist>(), &Specialist::ByteSizeLong,
                &Specialist::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Specialist, _impl_._cached_size_),
            false,
        },
        &Specialist::kDescriptorMethods,
        &descriptor_table_specialist_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Specialist::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 23, 2> Specialist::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Specialist, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Specialist>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Specialist, _impl_.name_)}},
    // int32 age = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Specialist, _impl_.age_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Specialist, _impl_.age_)}},
    // .Employee employee = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(Specialist, _impl_.employee_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Specialist, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 age = 2;
    {PROTOBUF_FIELD_OFFSET(Specialist, _impl_.age_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .Employee employee = 3;
    {PROTOBUF_FIELD_OFFSET(Specialist, _impl_.employee_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Employee>()},
  }}, {{
    "\12\4\0\0\0\0\0\0"
    "Specialist"
    "name"
  }},
};

PROTOBUF_NOINLINE void Specialist::Clear() {
// @@protoc_insertion_point(message_clear_start:Specialist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.employee_ != nullptr);
    _impl_.employee_->Clear();
  }
  _impl_.age_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Specialist::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Specialist& this_ = static_cast<const Specialist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Specialist::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Specialist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Specialist)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Specialist.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 age = 2;
          if (this_._internal_age() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_age(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Employee employee = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.employee_, this_._impl_.employee_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Specialist)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Specialist::ByteSizeLong(const MessageLite& base) {
          const Specialist& this_ = static_cast<const Specialist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Specialist::ByteSizeLong() const {
          const Specialist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Specialist)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .Employee employee = 3;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.employee_);
            }
          }
           {
            // int32 age = 2;
            if (this_._internal_age() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_age());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Specialist::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Specialist*>(&to_msg);
  auto& from = static_cast<const Specialist&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Specialist)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.employee_ != nullptr);
    if (_this->_impl_.employee_ == nullptr) {
      _this->_impl_.employee_ =
          ::google::protobuf::Message::CopyConstruct<::Employee>(arena, *from._impl_.employee_);
    } else {
      _this->_impl_.employee_->MergeFrom(*from._impl_.employee_);
    }
  }
  if (from._internal_age() != 0) {
    _this->_impl_.age_ = from._impl_.age_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Specialist::CopyFrom(const Specialist& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Specialist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Specialist::InternalSwap(Specialist* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Specialist, _impl_.age_)
      + sizeof(Specialist::_impl_.age_)
      - PROTOBUF_FIELD_OFFSET(Specialist, _impl_.employee_)>(
          reinterpret_cast<char*>(&_impl_.employee_),
          reinterpret_cast<char*>(&other->_impl_.employee_));
}

::google::protobuf::Metadata Specialist::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_specialist_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
