// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: encode.proto
// Protobuf C++ Version: 5.28.3

#include "encode.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MyVarint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num2_{::int64_t{0}},
        num1_{0},
        num3_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MyVarint::MyVarint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MyVarintDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MyVarintDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MyVarintDefaultTypeInternal() {}
  union {
    MyVarint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MyVarintDefaultTypeInternal _MyVarint_default_instance_;

inline constexpr MyLen::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MyLen::MyLen(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MyLenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MyLenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MyLenDefaultTypeInternal() {}
  union {
    MyLen _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MyLenDefaultTypeInternal _MyLen_default_instance_;

inline constexpr MyFixed::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num2_{::uint64_t{0u}},
        num1_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MyFixed::MyFixed(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MyFixedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MyFixedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MyFixedDefaultTypeInternal() {}
  union {
    MyFixed _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MyFixedDefaultTypeInternal _MyFixed_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR MyCustom_Num2Entry_DoNotUse::MyCustom_Num2Entry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : MyCustom_Num2Entry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : MyCustom_Num2Entry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct MyCustom_Num2Entry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MyCustom_Num2Entry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MyCustom_Num2Entry_DoNotUseDefaultTypeInternal() {}
  union {
    MyCustom_Num2Entry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MyCustom_Num2Entry_DoNotUseDefaultTypeInternal _MyCustom_Num2Entry_DoNotUse_default_instance_;

inline constexpr MyCustom::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num1_{},
        _num1_cached_byte_size_{0},
        num2_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MyCustom::MyCustom(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MyCustomDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MyCustomDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MyCustomDefaultTypeInternal() {}
  union {
    MyCustom _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MyCustomDefaultTypeInternal _MyCustom_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_encode_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_encode_2eproto = nullptr;
const ::uint32_t
    TableStruct_encode_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MyVarint, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MyVarint, _impl_.num1_),
        PROTOBUF_FIELD_OFFSET(::MyVarint, _impl_.num2_),
        PROTOBUF_FIELD_OFFSET(::MyVarint, _impl_.num3_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MyFixed, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MyFixed, _impl_.num1_),
        PROTOBUF_FIELD_OFFSET(::MyFixed, _impl_.num2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MyLen, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MyLen, _impl_.num1_),
        PROTOBUF_FIELD_OFFSET(::MyCustom_Num2Entry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MyCustom_Num2Entry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MyCustom_Num2Entry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::MyCustom_Num2Entry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MyCustom, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MyCustom, _impl_.num1_),
        PROTOBUF_FIELD_OFFSET(::MyCustom, _impl_.num2_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MyVarint)},
        {11, -1, -1, sizeof(::MyFixed)},
        {21, -1, -1, sizeof(::MyLen)},
        {30, 40, -1, sizeof(::MyCustom_Num2Entry_DoNotUse)},
        {42, -1, -1, sizeof(::MyCustom)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_MyVarint_default_instance_._instance,
    &::_MyFixed_default_instance_._instance,
    &::_MyLen_default_instance_._instance,
    &::_MyCustom_Num2Entry_DoNotUse_default_instance_._instance,
    &::_MyCustom_default_instance_._instance,
};
const char descriptor_table_protodef_encode_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014encode.proto\"4\n\010MyVarint\022\014\n\004num1\030\001 \001(\005"
    "\022\014\n\004num2\030\002 \001(\003\022\014\n\004num3\030\003 \001(\010\"%\n\007MyFixed\022"
    "\014\n\004num1\030\001 \001(\007\022\014\n\004num2\030\002 \001(\006\"\025\n\005MyLen\022\014\n\004"
    "num1\030\001 \001(\t\"h\n\010MyCustom\022\014\n\004num1\030\001 \003(\005\022!\n\004"
    "num2\030\002 \003(\0132\023.MyCustom.Num2Entry\032+\n\tNum2E"
    "ntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_encode_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_encode_2eproto = {
    false,
    false,
    244,
    descriptor_table_protodef_encode_2eproto,
    "encode.proto",
    &descriptor_table_encode_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_encode_2eproto::offsets,
    file_level_enum_descriptors_encode_2eproto,
    file_level_service_descriptors_encode_2eproto,
};
// ===================================================================

class MyVarint::_Internal {
 public:
};

MyVarint::MyVarint(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyVarint)
}
MyVarint::MyVarint(
    ::google::protobuf::Arena* arena, const MyVarint& from)
    : MyVarint(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MyVarint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MyVarint::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num2_),
           0,
           offsetof(Impl_, num3_) -
               offsetof(Impl_, num2_) +
               sizeof(Impl_::num3_));
}
MyVarint::~MyVarint() {
  // @@protoc_insertion_point(destructor:MyVarint)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MyVarint::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MyVarint::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MyVarint_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MyVarint::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MyVarint>(),
            ::google::protobuf::Message::GetNewImpl<MyVarint>(),
            ::google::protobuf::Message::GetClearImpl<MyVarint>(), &MyVarint::ByteSizeLong,
                &MyVarint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MyVarint, _impl_._cached_size_),
            false,
        },
        &MyVarint::kDescriptorMethods,
        &descriptor_table_encode_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MyVarint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> MyVarint::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MyVarint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 num1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MyVarint, _impl_.num1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num1_)}},
    // int64 num2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MyVarint, _impl_.num2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num2_)}},
    // bool num3 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MyVarint, _impl_.num3_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num3_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 num1 = 1;
    {PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 num2 = 2;
    {PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool num3 = 3;
    {PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num3_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MyVarint::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVarint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.num2_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.num3_) -
      reinterpret_cast<char*>(&_impl_.num2_)) + sizeof(_impl_.num3_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MyVarint::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MyVarint& this_ = static_cast<const MyVarint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MyVarint::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MyVarint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MyVarint)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 num1 = 1;
          if (this_._internal_num1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_num1(), target);
          }

          // int64 num2 = 2;
          if (this_._internal_num2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_num2(), target);
          }

          // bool num3 = 3;
          if (this_._internal_num3() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_num3(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MyVarint)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MyVarint::ByteSizeLong(const MessageLite& base) {
          const MyVarint& this_ = static_cast<const MyVarint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MyVarint::ByteSizeLong() const {
          const MyVarint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MyVarint)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int64 num2 = 2;
            if (this_._internal_num2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_num2());
            }
            // int32 num1 = 1;
            if (this_._internal_num1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_num1());
            }
            // bool num3 = 3;
            if (this_._internal_num3() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MyVarint::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MyVarint*>(&to_msg);
  auto& from = static_cast<const MyVarint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyVarint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num2() != 0) {
    _this->_impl_.num2_ = from._impl_.num2_;
  }
  if (from._internal_num1() != 0) {
    _this->_impl_.num1_ = from._impl_.num1_;
  }
  if (from._internal_num3() != 0) {
    _this->_impl_.num3_ = from._impl_.num3_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MyVarint::CopyFrom(const MyVarint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVarint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MyVarint::InternalSwap(MyVarint* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num3_)
      + sizeof(MyVarint::_impl_.num3_)
      - PROTOBUF_FIELD_OFFSET(MyVarint, _impl_.num2_)>(
          reinterpret_cast<char*>(&_impl_.num2_),
          reinterpret_cast<char*>(&other->_impl_.num2_));
}

::google::protobuf::Metadata MyVarint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MyFixed::_Internal {
 public:
};

MyFixed::MyFixed(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyFixed)
}
MyFixed::MyFixed(
    ::google::protobuf::Arena* arena, const MyFixed& from)
    : MyFixed(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MyFixed::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MyFixed::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num2_),
           0,
           offsetof(Impl_, num1_) -
               offsetof(Impl_, num2_) +
               sizeof(Impl_::num1_));
}
MyFixed::~MyFixed() {
  // @@protoc_insertion_point(destructor:MyFixed)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MyFixed::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MyFixed::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MyFixed_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MyFixed::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MyFixed>(),
            ::google::protobuf::Message::GetNewImpl<MyFixed>(),
            ::google::protobuf::Message::GetClearImpl<MyFixed>(), &MyFixed::ByteSizeLong,
                &MyFixed::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MyFixed, _impl_._cached_size_),
            false,
        },
        &MyFixed::kDescriptorMethods,
        &descriptor_table_encode_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MyFixed::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MyFixed::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MyFixed>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // fixed64 num2 = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num2_)}},
    // fixed32 num1 = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // fixed32 num1 = 1;
    {PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // fixed64 num2 = 2;
    {PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MyFixed::Clear() {
// @@protoc_insertion_point(message_clear_start:MyFixed)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.num2_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.num1_) -
      reinterpret_cast<char*>(&_impl_.num2_)) + sizeof(_impl_.num1_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MyFixed::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MyFixed& this_ = static_cast<const MyFixed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MyFixed::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MyFixed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MyFixed)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // fixed32 num1 = 1;
          if (this_._internal_num1() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                1, this_._internal_num1(), target);
          }

          // fixed64 num2 = 2;
          if (this_._internal_num2() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed64ToArray(
                2, this_._internal_num2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MyFixed)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MyFixed::ByteSizeLong(const MessageLite& base) {
          const MyFixed& this_ = static_cast<const MyFixed&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MyFixed::ByteSizeLong() const {
          const MyFixed& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MyFixed)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // fixed64 num2 = 2;
            if (this_._internal_num2() != 0) {
              total_size += 9;
            }
            // fixed32 num1 = 1;
            if (this_._internal_num1() != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MyFixed::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MyFixed*>(&to_msg);
  auto& from = static_cast<const MyFixed&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyFixed)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num2() != 0) {
    _this->_impl_.num2_ = from._impl_.num2_;
  }
  if (from._internal_num1() != 0) {
    _this->_impl_.num1_ = from._impl_.num1_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MyFixed::CopyFrom(const MyFixed& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyFixed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MyFixed::InternalSwap(MyFixed* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num1_)
      + sizeof(MyFixed::_impl_.num1_)
      - PROTOBUF_FIELD_OFFSET(MyFixed, _impl_.num2_)>(
          reinterpret_cast<char*>(&_impl_.num2_),
          reinterpret_cast<char*>(&other->_impl_.num2_));
}

::google::protobuf::Metadata MyFixed::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MyLen::_Internal {
 public:
};

MyLen::MyLen(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyLen)
}
inline PROTOBUF_NDEBUG_INLINE MyLen::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MyLen& from_msg)
      : num1_(arena, from.num1_),
        _cached_size_{0} {}

MyLen::MyLen(
    ::google::protobuf::Arena* arena,
    const MyLen& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MyLen* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MyLen)
}
inline PROTOBUF_NDEBUG_INLINE MyLen::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : num1_(arena),
        _cached_size_{0} {}

inline void MyLen::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MyLen::~MyLen() {
  // @@protoc_insertion_point(destructor:MyLen)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MyLen::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.num1_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MyLen::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MyLen_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MyLen::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MyLen>(),
            ::google::protobuf::Message::GetNewImpl<MyLen>(),
            ::google::protobuf::Message::GetClearImpl<MyLen>(), &MyLen::ByteSizeLong,
                &MyLen::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MyLen, _impl_._cached_size_),
            false,
        },
        &MyLen::kDescriptorMethods,
        &descriptor_table_encode_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MyLen::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 18, 2> MyLen::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MyLen>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string num1 = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MyLen, _impl_.num1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string num1 = 1;
    {PROTOBUF_FIELD_OFFSET(MyLen, _impl_.num1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\5\4\0\0\0\0\0\0"
    "MyLen"
    "num1"
  }},
};

PROTOBUF_NOINLINE void MyLen::Clear() {
// @@protoc_insertion_point(message_clear_start:MyLen)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.num1_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MyLen::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MyLen& this_ = static_cast<const MyLen&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MyLen::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MyLen& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MyLen)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string num1 = 1;
          if (!this_._internal_num1().empty()) {
            const std::string& _s = this_._internal_num1();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyLen.num1");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MyLen)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MyLen::ByteSizeLong(const MessageLite& base) {
          const MyLen& this_ = static_cast<const MyLen&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MyLen::ByteSizeLong() const {
          const MyLen& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MyLen)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string num1 = 1;
            if (!this_._internal_num1().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_num1());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MyLen::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MyLen*>(&to_msg);
  auto& from = static_cast<const MyLen&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyLen)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_num1().empty()) {
    _this->_internal_set_num1(from._internal_num1());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MyLen::CopyFrom(const MyLen& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyLen)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MyLen::InternalSwap(MyLen* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.num1_, &other->_impl_.num1_, arena);
}

::google::protobuf::Metadata MyLen::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              MyCustom_Num2Entry_DoNotUse::MyCustom_Num2Entry_DoNotUse() : SuperType(_class_data_.base()) {}
              MyCustom_Num2Entry_DoNotUse::MyCustom_Num2Entry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              MyCustom_Num2Entry_DoNotUse::MyCustom_Num2Entry_DoNotUse() : SuperType() {}
              MyCustom_Num2Entry_DoNotUse::MyCustom_Num2Entry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  MyCustom_Num2Entry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_MyCustom_Num2Entry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &MyCustom_Num2Entry_DoNotUse::MergeImpl,
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          ::google::protobuf::Message::GetDeleteImpl<MyCustom_Num2Entry_DoNotUse>(),
                          ::google::protobuf::Message::GetNewImpl<MyCustom_Num2Entry_DoNotUse>(),
                          ::google::protobuf::Message::ClearImpl, ::google::protobuf::Message::ByteSizeLongImpl,
                              ::google::protobuf::Message::_InternalSerializeImpl,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &MyCustom_Num2Entry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_encode_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* MyCustom_Num2Entry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2> MyCustom_Num2Entry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MyCustom_Num2Entry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MyCustom_Num2Entry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(MyCustom_Num2Entry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\5\0\0\0\0\0"
    "MyCustom.Num2Entry"
    "value"
  }},
};

// ===================================================================

class MyCustom::_Internal {
 public:
};

MyCustom::MyCustom(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyCustom)
}
inline PROTOBUF_NDEBUG_INLINE MyCustom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MyCustom& from_msg)
      : num1_{visibility, arena, from.num1_},
        _num1_cached_byte_size_{0},
        num2_{visibility, arena, from.num2_},
        _cached_size_{0} {}

MyCustom::MyCustom(
    ::google::protobuf::Arena* arena,
    const MyCustom& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MyCustom* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MyCustom)
}
inline PROTOBUF_NDEBUG_INLINE MyCustom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : num1_{visibility, arena},
        _num1_cached_byte_size_{0},
        num2_{visibility, arena},
        _cached_size_{0} {}

inline void MyCustom::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MyCustom::~MyCustom() {
  // @@protoc_insertion_point(destructor:MyCustom)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MyCustom::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MyCustom::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_MyCustom_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &MyCustom::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<MyCustom>(),
            ::google::protobuf::Message::GetNewImpl<MyCustom>(),
            ::google::protobuf::Message::GetClearImpl<MyCustom>(), &MyCustom::ByteSizeLong,
                &MyCustom::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MyCustom, _impl_._cached_size_),
            false,
        },
        &MyCustom::kDescriptorMethods,
        &descriptor_table_encode_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MyCustom::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 21, 2> MyCustom::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MyCustom>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 num1 = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MyCustom, _impl_.num1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 num1 = 1;
    {PROTOBUF_FIELD_OFFSET(MyCustom, _impl_.num1_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // map<int32, string> num2 = 2;
    {PROTOBUF_FIELD_OFFSET(MyCustom, _impl_.num2_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(MyCustom()._impl_.num2_)>(
        1, 0, 0, 5,
        9)},
  }}, {{
    "\10\0\4\0\0\0\0\0"
    "MyCustom"
    "num2"
  }},
};

PROTOBUF_NOINLINE void MyCustom::Clear() {
// @@protoc_insertion_point(message_clear_start:MyCustom)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.num1_.Clear();
  _impl_.num2_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MyCustom::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MyCustom& this_ = static_cast<const MyCustom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MyCustom::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MyCustom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MyCustom)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated int32 num1 = 1;
          {
            int byte_size = this_._impl_._num1_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  1, this_._internal_num1(), byte_size, target);
            }
          }

          // map<int32, string> num2 = 2;
          if (!this_._internal_num2().empty()) {
            using MapType = ::google::protobuf::Map<::int32_t, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<::int32_t, std::string,
                                           _pbi::WireFormatLite::TYPE_INT32,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_num2();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyCustom.num2");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyCustom.num2");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MyCustom)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MyCustom::ByteSizeLong(const MessageLite& base) {
          const MyCustom& this_ = static_cast<const MyCustom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MyCustom::ByteSizeLong() const {
          const MyCustom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MyCustom)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 num1 = 1;
             {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_num1())
              ;
              this_._impl_._num1_cached_byte_size_.Set(
                  ::_pbi::ToCachedSize(data_size));
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
            // map<int32, string> num2 = 2;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_num2_size());
              for (const auto& entry : this_._internal_num2()) {
                total_size += _pbi::MapEntryFuncs<::int32_t, std::string,
                                               _pbi::WireFormatLite::TYPE_INT32,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MyCustom::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MyCustom*>(&to_msg);
  auto& from = static_cast<const MyCustom&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyCustom)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_num1()->MergeFrom(from._internal_num1());
  _this->_impl_.num2_.MergeFrom(from._impl_.num2_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MyCustom::CopyFrom(const MyCustom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyCustom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MyCustom::InternalSwap(MyCustom* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.num1_.InternalSwap(&other->_impl_.num1_);
  _impl_.num2_.InternalSwap(&other->_impl_.num2_);
}

::google::protobuf::Metadata MyCustom::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_encode_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
