// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: encode.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_encode_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_encode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_encode_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_encode_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_encode_2eproto;
class MyCustom;
struct MyCustomDefaultTypeInternal;
extern MyCustomDefaultTypeInternal _MyCustom_default_instance_;
class MyCustom_Num2Entry_DoNotUse;
struct MyCustom_Num2Entry_DoNotUseDefaultTypeInternal;
extern MyCustom_Num2Entry_DoNotUseDefaultTypeInternal _MyCustom_Num2Entry_DoNotUse_default_instance_;
class MyFixed;
struct MyFixedDefaultTypeInternal;
extern MyFixedDefaultTypeInternal _MyFixed_default_instance_;
class MyLen;
struct MyLenDefaultTypeInternal;
extern MyLenDefaultTypeInternal _MyLen_default_instance_;
class MyVarint;
struct MyVarintDefaultTypeInternal;
extern MyVarintDefaultTypeInternal _MyVarint_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class MyVarint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MyVarint) */ {
 public:
  inline MyVarint() : MyVarint(nullptr) {}
  ~MyVarint() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MyVarint(
      ::google::protobuf::internal::ConstantInitialized);

  inline MyVarint(const MyVarint& from) : MyVarint(nullptr, from) {}
  inline MyVarint(MyVarint&& from) noexcept
      : MyVarint(nullptr, std::move(from)) {}
  inline MyVarint& operator=(const MyVarint& from) {
    CopyFrom(from);
    return *this;
  }
  inline MyVarint& operator=(MyVarint&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MyVarint& default_instance() {
    return *internal_default_instance();
  }
  static inline const MyVarint* internal_default_instance() {
    return reinterpret_cast<const MyVarint*>(
        &_MyVarint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MyVarint& a, MyVarint& b) { a.Swap(&b); }
  inline void Swap(MyVarint* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MyVarint* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MyVarint* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MyVarint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MyVarint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MyVarint& from) { MyVarint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MyVarint* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MyVarint"; }

 protected:
  explicit MyVarint(::google::protobuf::Arena* arena);
  MyVarint(::google::protobuf::Arena* arena, const MyVarint& from);
  MyVarint(::google::protobuf::Arena* arena, MyVarint&& from) noexcept
      : MyVarint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNum2FieldNumber = 2,
    kNum1FieldNumber = 1,
    kNum3FieldNumber = 3,
  };
  // int64 num2 = 2;
  void clear_num2() ;
  ::int64_t num2() const;
  void set_num2(::int64_t value);

  private:
  ::int64_t _internal_num2() const;
  void _internal_set_num2(::int64_t value);

  public:
  // int32 num1 = 1;
  void clear_num1() ;
  ::int32_t num1() const;
  void set_num1(::int32_t value);

  private:
  ::int32_t _internal_num1() const;
  void _internal_set_num1(::int32_t value);

  public:
  // bool num3 = 3;
  void clear_num3() ;
  bool num3() const;
  void set_num3(bool value);

  private:
  bool _internal_num3() const;
  void _internal_set_num3(bool value);

  public:
  // @@protoc_insertion_point(class_scope:MyVarint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MyVarint_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MyVarint& from_msg);
    ::int64_t num2_;
    ::int32_t num1_;
    bool num3_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_encode_2eproto;
};
// -------------------------------------------------------------------

class MyLen final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MyLen) */ {
 public:
  inline MyLen() : MyLen(nullptr) {}
  ~MyLen() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MyLen(
      ::google::protobuf::internal::ConstantInitialized);

  inline MyLen(const MyLen& from) : MyLen(nullptr, from) {}
  inline MyLen(MyLen&& from) noexcept
      : MyLen(nullptr, std::move(from)) {}
  inline MyLen& operator=(const MyLen& from) {
    CopyFrom(from);
    return *this;
  }
  inline MyLen& operator=(MyLen&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MyLen& default_instance() {
    return *internal_default_instance();
  }
  static inline const MyLen* internal_default_instance() {
    return reinterpret_cast<const MyLen*>(
        &_MyLen_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MyLen& a, MyLen& b) { a.Swap(&b); }
  inline void Swap(MyLen* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MyLen* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MyLen* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MyLen>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MyLen& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MyLen& from) { MyLen::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MyLen* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MyLen"; }

 protected:
  explicit MyLen(::google::protobuf::Arena* arena);
  MyLen(::google::protobuf::Arena* arena, const MyLen& from);
  MyLen(::google::protobuf::Arena* arena, MyLen&& from) noexcept
      : MyLen(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNum1FieldNumber = 1,
  };
  // string num1 = 1;
  void clear_num1() ;
  const std::string& num1() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_num1(Arg_&& arg, Args_... args);
  std::string* mutable_num1();
  PROTOBUF_NODISCARD std::string* release_num1();
  void set_allocated_num1(std::string* value);

  private:
  const std::string& _internal_num1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_num1(
      const std::string& value);
  std::string* _internal_mutable_num1();

  public:
  // @@protoc_insertion_point(class_scope:MyLen)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      18, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MyLen_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MyLen& from_msg);
    ::google::protobuf::internal::ArenaStringPtr num1_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_encode_2eproto;
};
// -------------------------------------------------------------------

class MyFixed final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MyFixed) */ {
 public:
  inline MyFixed() : MyFixed(nullptr) {}
  ~MyFixed() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MyFixed(
      ::google::protobuf::internal::ConstantInitialized);

  inline MyFixed(const MyFixed& from) : MyFixed(nullptr, from) {}
  inline MyFixed(MyFixed&& from) noexcept
      : MyFixed(nullptr, std::move(from)) {}
  inline MyFixed& operator=(const MyFixed& from) {
    CopyFrom(from);
    return *this;
  }
  inline MyFixed& operator=(MyFixed&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MyFixed& default_instance() {
    return *internal_default_instance();
  }
  static inline const MyFixed* internal_default_instance() {
    return reinterpret_cast<const MyFixed*>(
        &_MyFixed_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MyFixed& a, MyFixed& b) { a.Swap(&b); }
  inline void Swap(MyFixed* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MyFixed* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MyFixed* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MyFixed>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MyFixed& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MyFixed& from) { MyFixed::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MyFixed* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MyFixed"; }

 protected:
  explicit MyFixed(::google::protobuf::Arena* arena);
  MyFixed(::google::protobuf::Arena* arena, const MyFixed& from);
  MyFixed(::google::protobuf::Arena* arena, MyFixed&& from) noexcept
      : MyFixed(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNum2FieldNumber = 2,
    kNum1FieldNumber = 1,
  };
  // fixed64 num2 = 2;
  void clear_num2() ;
  ::uint64_t num2() const;
  void set_num2(::uint64_t value);

  private:
  ::uint64_t _internal_num2() const;
  void _internal_set_num2(::uint64_t value);

  public:
  // fixed32 num1 = 1;
  void clear_num1() ;
  ::uint32_t num1() const;
  void set_num1(::uint32_t value);

  private:
  ::uint32_t _internal_num1() const;
  void _internal_set_num1(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MyFixed)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MyFixed_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MyFixed& from_msg);
    ::uint64_t num2_;
    ::uint32_t num1_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_encode_2eproto;
};
// -------------------------------------------------------------------

class MyCustom_Num2Entry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          MyCustom_Num2Entry_DoNotUse, ::int32_t, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      MyCustom_Num2Entry_DoNotUse, ::int32_t, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  MyCustom_Num2Entry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MyCustom_Num2Entry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit MyCustom_Num2Entry_DoNotUse(::google::protobuf::Arena* arena);
  static const MyCustom_Num2Entry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const MyCustom_Num2Entry_DoNotUse*>(
        &_MyCustom_Num2Entry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      32, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_encode_2eproto;
};
// -------------------------------------------------------------------

class MyCustom final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MyCustom) */ {
 public:
  inline MyCustom() : MyCustom(nullptr) {}
  ~MyCustom() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MyCustom(
      ::google::protobuf::internal::ConstantInitialized);

  inline MyCustom(const MyCustom& from) : MyCustom(nullptr, from) {}
  inline MyCustom(MyCustom&& from) noexcept
      : MyCustom(nullptr, std::move(from)) {}
  inline MyCustom& operator=(const MyCustom& from) {
    CopyFrom(from);
    return *this;
  }
  inline MyCustom& operator=(MyCustom&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MyCustom& default_instance() {
    return *internal_default_instance();
  }
  static inline const MyCustom* internal_default_instance() {
    return reinterpret_cast<const MyCustom*>(
        &_MyCustom_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(MyCustom& a, MyCustom& b) { a.Swap(&b); }
  inline void Swap(MyCustom* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MyCustom* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MyCustom* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MyCustom>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MyCustom& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MyCustom& from) { MyCustom::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MyCustom* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MyCustom"; }

 protected:
  explicit MyCustom(::google::protobuf::Arena* arena);
  MyCustom(::google::protobuf::Arena* arena, const MyCustom& from);
  MyCustom(::google::protobuf::Arena* arena, MyCustom&& from) noexcept
      : MyCustom(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNum1FieldNumber = 1,
    kNum2FieldNumber = 2,
  };
  // repeated int32 num1 = 1;
  int num1_size() const;
  private:
  int _internal_num1_size() const;

  public:
  void clear_num1() ;
  ::int32_t num1(int index) const;
  void set_num1(int index, ::int32_t value);
  void add_num1(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& num1() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_num1();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_num1() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_num1();

  public:
  // map<int32, string> num2 = 2;
  int num2_size() const;
  private:
  int _internal_num2_size() const;

  public:
  void clear_num2() ;
  const ::google::protobuf::Map<::int32_t, std::string>& num2() const;
  ::google::protobuf::Map<::int32_t, std::string>* mutable_num2();

  private:
  const ::google::protobuf::Map<::int32_t, std::string>& _internal_num2() const;
  ::google::protobuf::Map<::int32_t, std::string>* _internal_mutable_num2();

  public:
  // @@protoc_insertion_point(class_scope:MyCustom)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 1,
      21, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MyCustom_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MyCustom& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> num1_;
    mutable ::google::protobuf::internal::CachedSize _num1_cached_byte_size_;
    ::google::protobuf::internal::MapField<MyCustom_Num2Entry_DoNotUse, ::int32_t, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        num2_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_encode_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MyVarint

// int32 num1 = 1;
inline void MyVarint::clear_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = 0;
}
inline ::int32_t MyVarint::num1() const {
  // @@protoc_insertion_point(field_get:MyVarint.num1)
  return _internal_num1();
}
inline void MyVarint::set_num1(::int32_t value) {
  _internal_set_num1(value);
  // @@protoc_insertion_point(field_set:MyVarint.num1)
}
inline ::int32_t MyVarint::_internal_num1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num1_;
}
inline void MyVarint::_internal_set_num1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = value;
}

// int64 num2 = 2;
inline void MyVarint::clear_num2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = ::int64_t{0};
}
inline ::int64_t MyVarint::num2() const {
  // @@protoc_insertion_point(field_get:MyVarint.num2)
  return _internal_num2();
}
inline void MyVarint::set_num2(::int64_t value) {
  _internal_set_num2(value);
  // @@protoc_insertion_point(field_set:MyVarint.num2)
}
inline ::int64_t MyVarint::_internal_num2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num2_;
}
inline void MyVarint::_internal_set_num2(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = value;
}

// bool num3 = 3;
inline void MyVarint::clear_num3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num3_ = false;
}
inline bool MyVarint::num3() const {
  // @@protoc_insertion_point(field_get:MyVarint.num3)
  return _internal_num3();
}
inline void MyVarint::set_num3(bool value) {
  _internal_set_num3(value);
  // @@protoc_insertion_point(field_set:MyVarint.num3)
}
inline bool MyVarint::_internal_num3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num3_;
}
inline void MyVarint::_internal_set_num3(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num3_ = value;
}

// -------------------------------------------------------------------

// MyFixed

// fixed32 num1 = 1;
inline void MyFixed::clear_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = 0u;
}
inline ::uint32_t MyFixed::num1() const {
  // @@protoc_insertion_point(field_get:MyFixed.num1)
  return _internal_num1();
}
inline void MyFixed::set_num1(::uint32_t value) {
  _internal_set_num1(value);
  // @@protoc_insertion_point(field_set:MyFixed.num1)
}
inline ::uint32_t MyFixed::_internal_num1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num1_;
}
inline void MyFixed::_internal_set_num1(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = value;
}

// fixed64 num2 = 2;
inline void MyFixed::clear_num2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = ::uint64_t{0u};
}
inline ::uint64_t MyFixed::num2() const {
  // @@protoc_insertion_point(field_get:MyFixed.num2)
  return _internal_num2();
}
inline void MyFixed::set_num2(::uint64_t value) {
  _internal_set_num2(value);
  // @@protoc_insertion_point(field_set:MyFixed.num2)
}
inline ::uint64_t MyFixed::_internal_num2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num2_;
}
inline void MyFixed::_internal_set_num2(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = value;
}

// -------------------------------------------------------------------

// MyLen

// string num1 = 1;
inline void MyLen::clear_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_.ClearToEmpty();
}
inline const std::string& MyLen::num1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MyLen.num1)
  return _internal_num1();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MyLen::set_num1(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MyLen.num1)
}
inline std::string* MyLen::mutable_num1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_num1();
  // @@protoc_insertion_point(field_mutable:MyLen.num1)
  return _s;
}
inline const std::string& MyLen::_internal_num1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num1_.Get();
}
inline void MyLen::_internal_set_num1(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_.Set(value, GetArena());
}
inline std::string* MyLen::_internal_mutable_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.num1_.Mutable( GetArena());
}
inline std::string* MyLen::release_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MyLen.num1)
  return _impl_.num1_.Release();
}
inline void MyLen::set_allocated_num1(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.num1_.IsDefault()) {
          _impl_.num1_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MyLen.num1)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MyCustom

// repeated int32 num1 = 1;
inline int MyCustom::_internal_num1_size() const {
  return _internal_num1().size();
}
inline int MyCustom::num1_size() const {
  return _internal_num1_size();
}
inline void MyCustom::clear_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_.Clear();
}
inline ::int32_t MyCustom::num1(int index) const {
  // @@protoc_insertion_point(field_get:MyCustom.num1)
  return _internal_num1().Get(index);
}
inline void MyCustom::set_num1(int index, ::int32_t value) {
  _internal_mutable_num1()->Set(index, value);
  // @@protoc_insertion_point(field_set:MyCustom.num1)
}
inline void MyCustom::add_num1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_num1()->Add(value);
  // @@protoc_insertion_point(field_add:MyCustom.num1)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& MyCustom::num1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:MyCustom.num1)
  return _internal_num1();
}
inline ::google::protobuf::RepeatedField<::int32_t>* MyCustom::mutable_num1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:MyCustom.num1)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_num1();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
MyCustom::_internal_num1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num1_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* MyCustom::_internal_mutable_num1() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.num1_;
}

// map<int32, string> num2 = 2;
inline int MyCustom::_internal_num2_size() const {
  return _internal_num2().size();
}
inline int MyCustom::num2_size() const {
  return _internal_num2_size();
}
inline void MyCustom::clear_num2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, std::string>& MyCustom::_internal_num2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num2_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, std::string>& MyCustom::num2() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:MyCustom.num2)
  return _internal_num2();
}
inline ::google::protobuf::Map<::int32_t, std::string>* MyCustom::_internal_mutable_num2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.num2_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, std::string>* MyCustom::mutable_num2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:MyCustom.num2)
  return _internal_mutable_num2();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_encode_2eproto_2epb_2eh
