// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sample.proto
// Protobuf C++ Version: 5.28.3

#include "sample.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
              template <typename>
PROTOBUF_CONSTEXPR Demo_MpsiEntry_DoNotUse::Demo_MpsiEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Demo_MpsiEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Demo_MpsiEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Demo_MpsiEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Demo_MpsiEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Demo_MpsiEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Demo_MpsiEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Demo_MpsiEntry_DoNotUseDefaultTypeInternal _Demo_MpsiEntry_DoNotUse_default_instance_;

inline constexpr Custom::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : attr1_{0},
        attr2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Custom::Custom(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CustomDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomDefaultTypeInternal() {}
  union {
    Custom _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomDefaultTypeInternal _Custom_default_instance_;

inline constexpr Demo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rept_{},
        _rept_cached_byte_size_{0},
        mpsi_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cust_{nullptr},
        numb_{0},
        week_{static_cast< ::Week >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Demo::Demo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DemoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DemoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DemoDefaultTypeInternal() {}
  union {
    Demo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DemoDefaultTypeInternal _Demo_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_sample_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sample_2eproto = nullptr;
const ::uint32_t
    TableStruct_sample_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Custom, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Custom, _impl_.attr1_),
        PROTOBUF_FIELD_OFFSET(::Custom, _impl_.attr2_),
        PROTOBUF_FIELD_OFFSET(::Demo_MpsiEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Demo_MpsiEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Demo_MpsiEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Demo_MpsiEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Demo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.numb_),
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.week_),
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.rept_),
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.mpsi_),
        PROTOBUF_FIELD_OFFSET(::Demo, _impl_.cust_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Custom)},
        {10, 20, -1, sizeof(::Demo_MpsiEntry_DoNotUse)},
        {22, 36, -1, sizeof(::Demo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Custom_default_instance_._instance,
    &::_Demo_MpsiEntry_DoNotUse_default_instance_._instance,
    &::_Demo_default_instance_._instance,
};
const char descriptor_table_protodef_sample_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014sample.proto\"&\n\006Custom\022\r\n\005attr1\030\001 \001(\005\022"
    "\r\n\005attr2\030\002 \001(\005\"\250\001\n\004Demo\022\014\n\004name\030\001 \001(\t\022\014\n"
    "\004numb\030\002 \001(\005\022\023\n\004week\030\003 \001(\0162\005.Week\022\014\n\004rept"
    "\030\004 \003(\005\022\035\n\004mpsi\030\005 \003(\0132\017.Demo.MpsiEntry\022\025\n"
    "\004cust\030\006 \001(\0132\007.Custom\032+\n\tMpsiEntry\022\013\n\003key"
    "\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001*E\n\004Week\022\007\n\003Mon"
    "\020\000\022\007\n\003Tue\020\001\022\007\n\003Wed\020\002\022\007\n\003Thu\020\003\022\007\n\003Fri\020\004\022\007"
    "\n\003Sat\020\005\022\007\n\003Sun\020\006b\006proto3"
};
static ::absl::once_flag descriptor_table_sample_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sample_2eproto = {
    false,
    false,
    304,
    descriptor_table_protodef_sample_2eproto,
    "sample.proto",
    &descriptor_table_sample_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_sample_2eproto::offsets,
    file_level_enum_descriptors_sample_2eproto,
    file_level_service_descriptors_sample_2eproto,
};
const ::google::protobuf::EnumDescriptor* Week_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_sample_2eproto);
  return file_level_enum_descriptors_sample_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Week_internal_data_[] = {
    458752u, 0u, };
bool Week_IsValid(int value) {
  return 0 <= value && value <= 6;
}
// ===================================================================

class Custom::_Internal {
 public:
};

Custom::Custom(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Custom)
}
Custom::Custom(
    ::google::protobuf::Arena* arena, const Custom& from)
    : Custom(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Custom::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Custom::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, attr1_),
           0,
           offsetof(Impl_, attr2_) -
               offsetof(Impl_, attr1_) +
               sizeof(Impl_::attr2_));
}
Custom::~Custom() {
  // @@protoc_insertion_point(destructor:Custom)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Custom::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Custom::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Custom_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Custom::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Custom>(),
            ::google::protobuf::Message::GetNewImpl<Custom>(),
            ::google::protobuf::Message::GetClearImpl<Custom>(), &Custom::ByteSizeLong,
                &Custom::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Custom, _impl_._cached_size_),
            false,
        },
        &Custom::kDescriptorMethods,
        &descriptor_table_sample_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Custom::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Custom::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Custom>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 attr2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Custom, _impl_.attr2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr2_)}},
    // int32 attr1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Custom, _impl_.attr1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 attr1 = 1;
    {PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 attr2 = 2;
    {PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Custom::Clear() {
// @@protoc_insertion_point(message_clear_start:Custom)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.attr1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.attr2_) -
      reinterpret_cast<char*>(&_impl_.attr1_)) + sizeof(_impl_.attr2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Custom::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Custom& this_ = static_cast<const Custom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Custom::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Custom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Custom)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 attr1 = 1;
          if (this_._internal_attr1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_attr1(), target);
          }

          // int32 attr2 = 2;
          if (this_._internal_attr2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_attr2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Custom)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Custom::ByteSizeLong(const MessageLite& base) {
          const Custom& this_ = static_cast<const Custom&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Custom::ByteSizeLong() const {
          const Custom& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Custom)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 attr1 = 1;
            if (this_._internal_attr1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_attr1());
            }
            // int32 attr2 = 2;
            if (this_._internal_attr2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_attr2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Custom::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Custom*>(&to_msg);
  auto& from = static_cast<const Custom&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Custom)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_attr1() != 0) {
    _this->_impl_.attr1_ = from._impl_.attr1_;
  }
  if (from._internal_attr2() != 0) {
    _this->_impl_.attr2_ = from._impl_.attr2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Custom::CopyFrom(const Custom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Custom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Custom::InternalSwap(Custom* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr2_)
      + sizeof(Custom::_impl_.attr2_)
      - PROTOBUF_FIELD_OFFSET(Custom, _impl_.attr1_)>(
          reinterpret_cast<char*>(&_impl_.attr1_),
          reinterpret_cast<char*>(&other->_impl_.attr1_));
}

::google::protobuf::Metadata Custom::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Demo_MpsiEntry_DoNotUse::Demo_MpsiEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Demo_MpsiEntry_DoNotUse::Demo_MpsiEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Demo_MpsiEntry_DoNotUse::Demo_MpsiEntry_DoNotUse() : SuperType() {}
              Demo_MpsiEntry_DoNotUse::Demo_MpsiEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  Demo_MpsiEntry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_Demo_MpsiEntry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &Demo_MpsiEntry_DoNotUse::MergeImpl,
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          ::google::protobuf::Message::GetDeleteImpl<Demo_MpsiEntry_DoNotUse>(),
                          ::google::protobuf::Message::GetNewImpl<Demo_MpsiEntry_DoNotUse>(),
                          ::google::protobuf::Message::ClearImpl, ::google::protobuf::Message::ByteSizeLongImpl,
                              ::google::protobuf::Message::_InternalSerializeImpl,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &Demo_MpsiEntry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_sample_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* Demo_MpsiEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 26, 2> Demo_MpsiEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Demo_MpsiEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Demo_MpsiEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(Demo_MpsiEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\16\3\0\0\0\0\0\0"
    "Demo.MpsiEntry"
    "key"
  }},
};

// ===================================================================

class Demo::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Demo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Demo, _impl_._has_bits_);
};

Demo::Demo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Demo)
}
inline PROTOBUF_NDEBUG_INLINE Demo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Demo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rept_{visibility, arena, from.rept_},
        _rept_cached_byte_size_{0},
        mpsi_{visibility, arena, from.mpsi_},
        name_(arena, from.name_) {}

Demo::Demo(
    ::google::protobuf::Arena* arena,
    const Demo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Demo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.cust_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Custom>(
                              arena, *from._impl_.cust_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numb_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, numb_),
           offsetof(Impl_, week_) -
               offsetof(Impl_, numb_) +
               sizeof(Impl_::week_));

  // @@protoc_insertion_point(copy_constructor:Demo)
}
inline PROTOBUF_NDEBUG_INLINE Demo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        rept_{visibility, arena},
        _rept_cached_byte_size_{0},
        mpsi_{visibility, arena},
        name_(arena) {}

inline void Demo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cust_),
           0,
           offsetof(Impl_, week_) -
               offsetof(Impl_, cust_) +
               sizeof(Impl_::week_));
}
Demo::~Demo() {
  // @@protoc_insertion_point(destructor:Demo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Demo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.cust_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Demo::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Demo_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Demo::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Demo>(),
            ::google::protobuf::Message::GetNewImpl<Demo>(),
            ::google::protobuf::Message::GetClearImpl<Demo>(), &Demo::ByteSizeLong,
                &Demo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Demo, _impl_._cached_size_),
            false,
        },
        &Demo::kDescriptorMethods,
        &descriptor_table_sample_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Demo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 21, 2> Demo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Demo, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Demo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Demo, _impl_.name_)}},
    // int32 numb = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Demo, _impl_.numb_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Demo, _impl_.numb_)}},
    // .Week week = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Demo, _impl_.week_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Demo, _impl_.week_)}},
    // repeated int32 rept = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Demo, _impl_.rept_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // .Custom cust = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(Demo, _impl_.cust_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 numb = 2;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.numb_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .Week week = 3;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.week_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated int32 rept = 4;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.rept_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // map<string, int32> mpsi = 5;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.mpsi_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .Custom cust = 6;
    {PROTOBUF_FIELD_OFFSET(Demo, _impl_.cust_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Custom>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Demo()._impl_.mpsi_)>(
        1, 0, 0, 9,
        5)},
  }}, {{
    "\4\4\0\0\0\4\0\0"
    "Demo"
    "name"
    "mpsi"
  }},
};

PROTOBUF_NOINLINE void Demo::Clear() {
// @@protoc_insertion_point(message_clear_start:Demo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rept_.Clear();
  _impl_.mpsi_.Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.cust_ != nullptr);
    _impl_.cust_->Clear();
  }
  ::memset(&_impl_.numb_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.week_) -
      reinterpret_cast<char*>(&_impl_.numb_)) + sizeof(_impl_.week_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Demo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Demo& this_ = static_cast<const Demo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Demo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Demo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Demo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Demo.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 numb = 2;
          if (this_._internal_numb() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_numb(), target);
          }

          // .Week week = 3;
          if (this_._internal_week() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_week(), target);
          }

          // repeated int32 rept = 4;
          {
            int byte_size = this_._impl_._rept_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  4, this_._internal_rept(), byte_size, target);
            }
          }

          // map<string, int32> mpsi = 5;
          if (!this_._internal_mpsi().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT32>;
            const auto& field = this_._internal_mpsi();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    5, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Demo.mpsi");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    5, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Demo.mpsi");
              }
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Custom cust = 6;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.cust_, this_._impl_.cust_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Demo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Demo::ByteSizeLong(const MessageLite& base) {
          const Demo& this_ = static_cast<const Demo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Demo::ByteSizeLong() const {
          const Demo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Demo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 rept = 4;
             {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_rept())
              ;
              this_._impl_._rept_cached_byte_size_.Set(
                  ::_pbi::ToCachedSize(data_size));
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size))
              ;
              total_size += tag_size + data_size;
            }
            // map<string, int32> mpsi = 5;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_mpsi_size());
              for (const auto& entry : this_._internal_mpsi()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .Custom cust = 6;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cust_);
            }
          }
           {
            // int32 numb = 2;
            if (this_._internal_numb() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_numb());
            }
            // .Week week = 3;
            if (this_._internal_week() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_week());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Demo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Demo*>(&to_msg);
  auto& from = static_cast<const Demo&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Demo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_rept()->MergeFrom(from._internal_rept());
  _this->_impl_.mpsi_.MergeFrom(from._impl_.mpsi_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.cust_ != nullptr);
    if (_this->_impl_.cust_ == nullptr) {
      _this->_impl_.cust_ =
          ::google::protobuf::Message::CopyConstruct<::Custom>(arena, *from._impl_.cust_);
    } else {
      _this->_impl_.cust_->MergeFrom(*from._impl_.cust_);
    }
  }
  if (from._internal_numb() != 0) {
    _this->_impl_.numb_ = from._impl_.numb_;
  }
  if (from._internal_week() != 0) {
    _this->_impl_.week_ = from._impl_.week_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Demo::CopyFrom(const Demo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Demo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Demo::InternalSwap(Demo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.rept_.InternalSwap(&other->_impl_.rept_);
  _impl_.mpsi_.InternalSwap(&other->_impl_.mpsi_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Demo, _impl_.week_)
      + sizeof(Demo::_impl_.week_)
      - PROTOBUF_FIELD_OFFSET(Demo, _impl_.cust_)>(
          reinterpret_cast<char*>(&_impl_.cust_),
          reinterpret_cast<char*>(&other->_impl_.cust_));
}

::google::protobuf::Metadata Demo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_sample_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
