// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sample.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_sample_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_sample_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sample_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sample_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_sample_2eproto;
class Custom;
struct CustomDefaultTypeInternal;
extern CustomDefaultTypeInternal _Custom_default_instance_;
class Demo;
struct DemoDefaultTypeInternal;
extern DemoDefaultTypeInternal _Demo_default_instance_;
class Demo_MpsiEntry_DoNotUse;
struct Demo_MpsiEntry_DoNotUseDefaultTypeInternal;
extern Demo_MpsiEntry_DoNotUseDefaultTypeInternal _Demo_MpsiEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum Week : int {
  Mon = 0,
  Tue = 1,
  Wed = 2,
  Thu = 3,
  Fri = 4,
  Sat = 5,
  Sun = 6,
  Week_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  Week_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool Week_IsValid(int value);
extern const uint32_t Week_internal_data_[];
constexpr Week Week_MIN = static_cast<Week>(0);
constexpr Week Week_MAX = static_cast<Week>(6);
constexpr int Week_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor*
Week_descriptor();
template <typename T>
const std::string& Week_Name(T value) {
  static_assert(std::is_same<T, Week>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Week_Name().");
  return Week_Name(static_cast<Week>(value));
}
template <>
inline const std::string& Week_Name(Week value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Week_descriptor,
                                                 0, 6>(
      static_cast<int>(value));
}
inline bool Week_Parse(absl::string_view name, Week* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Week>(
      Week_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Demo_MpsiEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          Demo_MpsiEntry_DoNotUse, std::string, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      Demo_MpsiEntry_DoNotUse, std::string, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  Demo_MpsiEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Demo_MpsiEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Demo_MpsiEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Demo_MpsiEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Demo_MpsiEntry_DoNotUse*>(
        &_Demo_MpsiEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      26, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_sample_2eproto;
};
// -------------------------------------------------------------------

class Custom final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Custom) */ {
 public:
  inline Custom() : Custom(nullptr) {}
  ~Custom() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Custom(
      ::google::protobuf::internal::ConstantInitialized);

  inline Custom(const Custom& from) : Custom(nullptr, from) {}
  inline Custom(Custom&& from) noexcept
      : Custom(nullptr, std::move(from)) {}
  inline Custom& operator=(const Custom& from) {
    CopyFrom(from);
    return *this;
  }
  inline Custom& operator=(Custom&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Custom& default_instance() {
    return *internal_default_instance();
  }
  static inline const Custom* internal_default_instance() {
    return reinterpret_cast<const Custom*>(
        &_Custom_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Custom& a, Custom& b) { a.Swap(&b); }
  inline void Swap(Custom* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Custom* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Custom* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Custom>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Custom& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Custom& from) { Custom::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Custom* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Custom"; }

 protected:
  explicit Custom(::google::protobuf::Arena* arena);
  Custom(::google::protobuf::Arena* arena, const Custom& from);
  Custom(::google::protobuf::Arena* arena, Custom&& from) noexcept
      : Custom(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAttr1FieldNumber = 1,
    kAttr2FieldNumber = 2,
  };
  // int32 attr1 = 1;
  void clear_attr1() ;
  ::int32_t attr1() const;
  void set_attr1(::int32_t value);

  private:
  ::int32_t _internal_attr1() const;
  void _internal_set_attr1(::int32_t value);

  public:
  // int32 attr2 = 2;
  void clear_attr2() ;
  ::int32_t attr2() const;
  void set_attr2(::int32_t value);

  private:
  ::int32_t _internal_attr2() const;
  void _internal_set_attr2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Custom)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Custom_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Custom& from_msg);
    ::int32_t attr1_;
    ::int32_t attr2_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sample_2eproto;
};
// -------------------------------------------------------------------

class Demo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Demo) */ {
 public:
  inline Demo() : Demo(nullptr) {}
  ~Demo() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Demo(
      ::google::protobuf::internal::ConstantInitialized);

  inline Demo(const Demo& from) : Demo(nullptr, from) {}
  inline Demo(Demo&& from) noexcept
      : Demo(nullptr, std::move(from)) {}
  inline Demo& operator=(const Demo& from) {
    CopyFrom(from);
    return *this;
  }
  inline Demo& operator=(Demo&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Demo& default_instance() {
    return *internal_default_instance();
  }
  static inline const Demo* internal_default_instance() {
    return reinterpret_cast<const Demo*>(
        &_Demo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Demo& a, Demo& b) { a.Swap(&b); }
  inline void Swap(Demo* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Demo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Demo* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Demo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Demo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Demo& from) { Demo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Demo* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Demo"; }

 protected:
  explicit Demo(::google::protobuf::Arena* arena);
  Demo(::google::protobuf::Arena* arena, const Demo& from);
  Demo(::google::protobuf::Arena* arena, Demo&& from) noexcept
      : Demo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReptFieldNumber = 4,
    kMpsiFieldNumber = 5,
    kNameFieldNumber = 1,
    kCustFieldNumber = 6,
    kNumbFieldNumber = 2,
    kWeekFieldNumber = 3,
  };
  // repeated int32 rept = 4;
  int rept_size() const;
  private:
  int _internal_rept_size() const;

  public:
  void clear_rept() ;
  ::int32_t rept(int index) const;
  void set_rept(int index, ::int32_t value);
  void add_rept(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& rept() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_rept();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_rept() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_rept();

  public:
  // map<string, int32> mpsi = 5;
  int mpsi_size() const;
  private:
  int _internal_mpsi_size() const;

  public:
  void clear_mpsi() ;
  const ::google::protobuf::Map<std::string, ::int32_t>& mpsi() const;
  ::google::protobuf::Map<std::string, ::int32_t>* mutable_mpsi();

  private:
  const ::google::protobuf::Map<std::string, ::int32_t>& _internal_mpsi() const;
  ::google::protobuf::Map<std::string, ::int32_t>* _internal_mutable_mpsi();

  public:
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .Custom cust = 6;
  bool has_cust() const;
  void clear_cust() ;
  const ::Custom& cust() const;
  PROTOBUF_NODISCARD ::Custom* release_cust();
  ::Custom* mutable_cust();
  void set_allocated_cust(::Custom* value);
  void unsafe_arena_set_allocated_cust(::Custom* value);
  ::Custom* unsafe_arena_release_cust();

  private:
  const ::Custom& _internal_cust() const;
  ::Custom* _internal_mutable_cust();

  public:
  // int32 numb = 2;
  void clear_numb() ;
  ::int32_t numb() const;
  void set_numb(::int32_t value);

  private:
  ::int32_t _internal_numb() const;
  void _internal_set_numb(::int32_t value);

  public:
  // .Week week = 3;
  void clear_week() ;
  ::Week week() const;
  void set_week(::Week value);

  private:
  ::Week _internal_week() const;
  void _internal_set_week(::Week value);

  public:
  // @@protoc_insertion_point(class_scope:Demo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 2,
      21, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Demo_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Demo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> rept_;
    mutable ::google::protobuf::internal::CachedSize _rept_cached_byte_size_;
    ::google::protobuf::internal::MapField<Demo_MpsiEntry_DoNotUse, std::string, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        mpsi_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::Custom* cust_;
    ::int32_t numb_;
    int week_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sample_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Custom

// int32 attr1 = 1;
inline void Custom::clear_attr1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attr1_ = 0;
}
inline ::int32_t Custom::attr1() const {
  // @@protoc_insertion_point(field_get:Custom.attr1)
  return _internal_attr1();
}
inline void Custom::set_attr1(::int32_t value) {
  _internal_set_attr1(value);
  // @@protoc_insertion_point(field_set:Custom.attr1)
}
inline ::int32_t Custom::_internal_attr1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attr1_;
}
inline void Custom::_internal_set_attr1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attr1_ = value;
}

// int32 attr2 = 2;
inline void Custom::clear_attr2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attr2_ = 0;
}
inline ::int32_t Custom::attr2() const {
  // @@protoc_insertion_point(field_get:Custom.attr2)
  return _internal_attr2();
}
inline void Custom::set_attr2(::int32_t value) {
  _internal_set_attr2(value);
  // @@protoc_insertion_point(field_set:Custom.attr2)
}
inline ::int32_t Custom::_internal_attr2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attr2_;
}
inline void Custom::_internal_set_attr2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attr2_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Demo

// string name = 1;
inline void Demo::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Demo::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Demo.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Demo::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Demo.name)
}
inline std::string* Demo::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Demo.name)
  return _s;
}
inline const std::string& Demo::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Demo::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Demo::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Demo::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Demo.name)
  return _impl_.name_.Release();
}
inline void Demo::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Demo.name)
}

// int32 numb = 2;
inline void Demo::clear_numb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numb_ = 0;
}
inline ::int32_t Demo::numb() const {
  // @@protoc_insertion_point(field_get:Demo.numb)
  return _internal_numb();
}
inline void Demo::set_numb(::int32_t value) {
  _internal_set_numb(value);
  // @@protoc_insertion_point(field_set:Demo.numb)
}
inline ::int32_t Demo::_internal_numb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numb_;
}
inline void Demo::_internal_set_numb(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numb_ = value;
}

// .Week week = 3;
inline void Demo::clear_week() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.week_ = 0;
}
inline ::Week Demo::week() const {
  // @@protoc_insertion_point(field_get:Demo.week)
  return _internal_week();
}
inline void Demo::set_week(::Week value) {
  _internal_set_week(value);
  // @@protoc_insertion_point(field_set:Demo.week)
}
inline ::Week Demo::_internal_week() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Week>(_impl_.week_);
}
inline void Demo::_internal_set_week(::Week value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.week_ = value;
}

// repeated int32 rept = 4;
inline int Demo::_internal_rept_size() const {
  return _internal_rept().size();
}
inline int Demo::rept_size() const {
  return _internal_rept_size();
}
inline void Demo::clear_rept() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rept_.Clear();
}
inline ::int32_t Demo::rept(int index) const {
  // @@protoc_insertion_point(field_get:Demo.rept)
  return _internal_rept().Get(index);
}
inline void Demo::set_rept(int index, ::int32_t value) {
  _internal_mutable_rept()->Set(index, value);
  // @@protoc_insertion_point(field_set:Demo.rept)
}
inline void Demo::add_rept(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rept()->Add(value);
  // @@protoc_insertion_point(field_add:Demo.rept)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Demo::rept() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Demo.rept)
  return _internal_rept();
}
inline ::google::protobuf::RepeatedField<::int32_t>* Demo::mutable_rept()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Demo.rept)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rept();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Demo::_internal_rept() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rept_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* Demo::_internal_mutable_rept() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rept_;
}

// map<string, int32> mpsi = 5;
inline int Demo::_internal_mpsi_size() const {
  return _internal_mpsi().size();
}
inline int Demo::mpsi_size() const {
  return _internal_mpsi_size();
}
inline void Demo::clear_mpsi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mpsi_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Demo::_internal_mpsi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mpsi_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& Demo::mpsi() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Demo.mpsi)
  return _internal_mpsi();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Demo::_internal_mutable_mpsi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mpsi_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* Demo::mutable_mpsi() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Demo.mpsi)
  return _internal_mutable_mpsi();
}

// .Custom cust = 6;
inline bool Demo::has_cust() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.cust_ != nullptr);
  return value;
}
inline void Demo::clear_cust() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.cust_ != nullptr) _impl_.cust_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Custom& Demo::_internal_cust() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Custom* p = _impl_.cust_;
  return p != nullptr ? *p : reinterpret_cast<const ::Custom&>(::_Custom_default_instance_);
}
inline const ::Custom& Demo::cust() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Demo.cust)
  return _internal_cust();
}
inline void Demo::unsafe_arena_set_allocated_cust(::Custom* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.cust_);
  }
  _impl_.cust_ = reinterpret_cast<::Custom*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Demo.cust)
}
inline ::Custom* Demo::release_cust() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Custom* released = _impl_.cust_;
  _impl_.cust_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Custom* Demo::unsafe_arena_release_cust() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Demo.cust)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Custom* temp = _impl_.cust_;
  _impl_.cust_ = nullptr;
  return temp;
}
inline ::Custom* Demo::_internal_mutable_cust() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.cust_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Custom>(GetArena());
    _impl_.cust_ = reinterpret_cast<::Custom*>(p);
  }
  return _impl_.cust_;
}
inline ::Custom* Demo::mutable_cust() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Custom* _msg = _internal_mutable_cust();
  // @@protoc_insertion_point(field_mutable:Demo.cust)
  return _msg;
}
inline void Demo::set_allocated_cust(::Custom* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.cust_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.cust_ = reinterpret_cast<::Custom*>(value);
  // @@protoc_insertion_point(field_set_allocated:Demo.cust)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Week> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Week>() {
  return ::Week_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_sample_2eproto_2epb_2eh
